import { field, form, type GridTemplate, record, table, view } from "./types";

export const bookshopTemplate: GridTemplate = {
  id: "bookshop",
  name: "Bookshop inventory",
  description: "Books, authors, customers, orders, relations, lookups, rollups, views, forms, dashboards.",
  icon: "ti ti-books",
  baseName: "Bookshop",
  baseDescription: "Inventory and order tracking for a small bookshop.",
  tables: [
    {
      key: "authors",
      name: "Authors",
      description: "People who wrote the books.",
      fields: [
        { key: "name", name: "name", type: "text", config: { maxLength: 200 }, required: true, presentable: true, icon: "ti ti-user" },
        {
          key: "birth_year",
          name: "birth_year",
          type: "number",
          config: { min: 1000, max: 3000, integerOnly: true },
          icon: "ti ti-calendar",
        },
        {
          key: "country",
          name: "country",
          type: "select",
          icon: "ti ti-map-pin",
          config: {
            options: [
              { id: "de", label: "Germany", color: "#ef4444" },
              { id: "uk", label: "United Kingdom", color: "#3b82f6" },
              { id: "us", label: "United States", color: "#10b981" },
              { id: "jp", label: "Japan", color: "#f59e0b" },
            ],
          },
        },
        { key: "bio", name: "bio", type: "longtext", icon: "ti ti-notes" },
      ],
    },
    {
      key: "genres",
      name: "Genres",
      description: "Reusable genre catalog.",
      fields: [
        { key: "name", name: "name", type: "text", config: { maxLength: 80 }, required: true, presentable: true, icon: "ti ti-tag" },
        { key: "description", name: "description", type: "longtext", icon: "ti ti-align-left" },
      ],
    },
    {
      key: "books",
      name: "Books",
      description: "Catalog and inventory.",
      fields: [
        { key: "title", name: "title", type: "text", config: { maxLength: 200 }, required: true, presentable: true, icon: "ti ti-book" },
        { key: "description", name: "description", type: "longtext", icon: "ti ti-align-left" },
        {
          key: "author",
          name: "author",
          type: "relation",
          icon: "ti ti-user",
          config: { targetTableId: table("authors"), cardinality: "single" },
        },
        {
          key: "genre",
          name: "genre",
          type: "relation",
          icon: "ti ti-tags",
          config: { targetTableId: table("genres"), cardinality: "single" },
        },
        { key: "pages", name: "pages", type: "number", config: { min: 1, integerOnly: true }, icon: "ti ti-file-text" },
        {
          key: "price",
          name: "price",
          type: "number",
          config: { precision: 16, decimalPlaces: 2, unit: "EUR", unitPosition: "suffix" },
          icon: "ti ti-currency-euro",
        },
        { key: "published", name: "published", type: "date", icon: "ti ti-calendar" },
        { key: "in_stock", name: "in_stock", type: "boolean", defaultValue: true, icon: "ti ti-package" },
        {
          key: "tags",
          name: "tags",
          type: "select",
          icon: "ti ti-tags",
          config: {
            multiple: true,
            options: [
              { id: "classic", label: "Classic", color: "#f59e0b" },
              { id: "recommended", label: "Recommended", color: "#22c55e" },
              { id: "sale", label: "On sale", color: "#ef4444" },
            ],
          },
        },
        { key: "score", name: "score", type: "number", config: { min: 0, max: 5, integerOnly: true }, icon: "ti ti-star" },
        { key: "sku", name: "sku", type: "autonumber", icon: "ti ti-barcode" },
        {
          key: "author_country",
          name: "author_country",
          type: "lookup",
          config: { relationFieldId: field("books.author"), targetFieldId: field("authors.country") },
          icon: "ti ti-hierarchy",
        },
      ],
    },
    {
      key: "customers",
      name: "Customers",
      description: "Bookshop customers.",
      fields: [
        { key: "name", name: "name", type: "text", config: { maxLength: 200 }, required: true, presentable: true, icon: "ti ti-user" },
        { key: "email", name: "email", type: "text", config: { regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" }, icon: "ti ti-mail" },
        { key: "phone", name: "phone", type: "text", config: { maxLength: 40 }, icon: "ti ti-phone" },
        { key: "joined", name: "joined", type: "date", icon: "ti ti-calendar-plus" },
        { key: "notes", name: "notes", type: "longtext", icon: "ti ti-notes" },
        {
          key: "source",
          name: "source",
          type: "select",
          icon: "ti ti-route",
          config: {
            options: [
              { id: "website", label: "Website", color: "#3b82f6" },
              { id: "store", label: "In-store", color: "#22c55e" },
              { id: "referral", label: "Referral", color: "#a855f7" },
            ],
          },
        },
      ],
    },
    {
      key: "orders",
      name: "Orders",
      description: "Order lines.",
      fields: [
        { key: "order_no", name: "order_no", type: "autonumber", presentable: true, icon: "ti ti-hash" },
        {
          key: "customer",
          name: "customer",
          type: "relation",
          icon: "ti ti-user",
          config: { targetTableId: table("customers"), cardinality: "single" },
        },
        {
          key: "book",
          name: "book",
          type: "relation",
          icon: "ti ti-book",
          config: { targetTableId: table("books"), cardinality: "single" },
        },
        { key: "qty", name: "qty", type: "number", config: { min: 1, integerOnly: true }, icon: "ti ti-calculator" },
        {
          key: "line_total",
          name: "line_total",
          type: "number",
          config: { precision: 16, decimalPlaces: 2, unit: "EUR", unitPosition: "suffix" },
          icon: "ti ti-currency-euro",
        },
        { key: "ordered_at", name: "ordered_at", type: "date", icon: "ti ti-calendar" },
        {
          key: "status",
          name: "status",
          type: "select",
          icon: "ti ti-truck-delivery",
          config: {
            options: [
              { id: "new", label: "New", color: "#3b82f6" },
              { id: "shipped", label: "Shipped", color: "#f59e0b" },
              { id: "delivered", label: "Delivered", color: "#22c55e" },
            ],
          },
        },
        {
          key: "customer_name",
          name: "customer_name",
          type: "lookup",
          config: { relationFieldId: field("orders.customer"), targetFieldId: field("customers.name") },
          icon: "ti ti-hierarchy",
        },
        {
          key: "book_title",
          name: "book_title",
          type: "lookup",
          config: { relationFieldId: field("orders.book"), targetFieldId: field("books.title") },
          icon: "ti ti-hierarchy",
        },
      ],
    },
  ],
  records: [
    {
      key: "authors.tolkien",
      table: "authors",
      values: { name: "J.R.R. Tolkien", birth_year: 1892, country: ["uk"], bio: "Philologist; coined Middle-earth." },
    },
    {
      key: "authors.le_guin",
      table: "authors",
      values: { name: "Ursula K. Le Guin", birth_year: 1929, country: ["us"], bio: "SF/F that takes anthropology seriously." },
    },
    {
      key: "authors.christie",
      table: "authors",
      values: { name: "Agatha Christie", birth_year: 1890, country: ["uk"], bio: "Best-selling mystery novelist." },
    },
    { key: "genres.fantasy", table: "genres", values: { name: "Fantasy", description: "Worlds, magic, dragons." } },
    { key: "genres.scifi", table: "genres", values: { name: "Sci-Fi", description: "Speculative futures, hard tech." } },
    { key: "genres.mystery", table: "genres", values: { name: "Mystery", description: "Whodunits and noir." } },
    {
      key: "books.hobbit",
      table: "books",
      values: {
        title: "The Hobbit",
        description: "A compact fantasy classic.",
        author: [record("authors.tolkien")],
        genre: [record("genres.fantasy")],
        pages: 310,
        price: "9.99",
        published: "1937-09-21",
        in_stock: true,
        tags: ["classic", "recommended"],
        score: 5,
      },
    },
    {
      key: "books.left_hand",
      table: "books",
      values: {
        title: "The Left Hand of Darkness",
        author: [record("authors.le_guin")],
        genre: [record("genres.scifi")],
        pages: 304,
        price: "11.99",
        published: "1969-03-01",
        in_stock: true,
        tags: ["recommended"],
        score: 5,
      },
    },
    {
      key: "books.abc",
      table: "books",
      values: {
        title: "The ABC Murders",
        author: [record("authors.christie")],
        genre: [record("genres.mystery")],
        pages: 220,
        price: "8.50",
        published: "1936-01-06",
        in_stock: false,
        tags: [],
        score: 4,
      },
    },
    {
      key: "customers.alice",
      table: "customers",
      values: {
        name: "Alice Becker",
        email: "alice@example.com",
        phone: "+49 731 1234567",
        joined: "2025-03-12",
        notes: "Loves fantasy.",
        source: ["website"],
      },
    },
    {
      key: "customers.bob",
      table: "customers",
      values: { name: "Bob Schmidt", email: "bob@example.com", phone: "+49 731 7654321", joined: "2025-06-04", source: ["store"] },
    },
    {
      key: "orders.1",
      table: "orders",
      values: {
        customer: [record("customers.alice")],
        book: [record("books.hobbit")],
        qty: 2,
        line_total: "19.98",
        ordered_at: "2026-03-15",
        status: ["delivered"],
      },
    },
    {
      key: "orders.2",
      table: "orders",
      values: {
        customer: [record("customers.bob")],
        book: [record("books.abc")],
        qty: 1,
        line_total: "8.50",
        ordered_at: "2026-04-02",
        status: ["shipped"],
      },
    },
    {
      key: "orders.3",
      table: "orders",
      values: {
        customer: [record("customers.alice")],
        book: [record("books.left_hand")],
        qty: 1,
        line_total: "11.99",
        ordered_at: "2026-04-09",
        status: ["new"],
      },
    },
  ],
  views: [
    {
      key: "recent_books",
      table: "books",
      name: "Recent books",
      shared: true,
      query: {
        columns: [
          { fieldId: field("books.title") },
          { fieldId: field("books.author") },
          { fieldId: field("books.price") },
          { fieldId: field("books.published") },
        ],
        sort: [{ fieldId: field("books.published"), direction: "desc" }],
        limit: 20,
      },
    },
    {
      key: "books_per_author",
      table: "books",
      name: "Books per author",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("books.author") }],
        aggregations: [
          { fieldId: "*", agg: "count", label: "records" },
          { fieldId: field("books.pages"), agg: "sum", label: "sum pages" },
        ],
      },
    },
    {
      key: "orders_by_month",
      table: "orders",
      name: "Orders by month",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("orders.ordered_at"), granularity: "month" }],
        aggregations: [
          { fieldId: "*", agg: "count", label: "orders" },
          { fieldId: field("orders.line_total"), agg: "sum", label: "revenue" },
        ],
      },
    },
  ],
  forms: [
    {
      key: "new_order",
      table: "orders",
      name: "New order",
      config: {
        title: "New order",
        submitLabel: "Create order",
        successMessage: "Order created.",
        fields: [
          {
            kind: "user_input",
            fieldId: field("orders.customer"),
            label: "Customer",
            required: true,
            inlineCreate: {
              enabled: true,
              fields: [
                { fieldId: field("customers.name"), label: "Customer name", required: true },
                { fieldId: field("customers.email"), label: "Email" },
                { fieldId: field("customers.phone"), label: "Phone" },
              ],
            },
          },
          { kind: "user_input", fieldId: field("orders.book"), label: "Book", required: true },
          { kind: "user_input", fieldId: field("orders.qty"), label: "Quantity", required: true, defaultValue: 1 },
          { kind: "user_input", fieldId: field("orders.line_total"), label: "Line total", required: true },
          { kind: "form_value", fieldId: field("orders.status"), value: ["new"] },
        ],
      },
    },
    {
      key: "newsletter",
      table: "customers",
      name: "Newsletter signup",
      isPublic: true,
      config: {
        fields: [
          { kind: "user_input", fieldId: field("customers.name"), label: "Name", required: true },
          { kind: "user_input", fieldId: field("customers.email"), label: "Email", required: true },
          { kind: "user_input", fieldId: field("customers.notes"), label: "Notes" },
          { kind: "form_value", fieldId: field("customers.source"), value: ["website"] },
        ],
      },
    },
  ],
  dashboards: [
    {
      key: "sales",
      name: "Sales overview",
      description: "Revenue, orders, signup form, and embedded views.",
      shared: true,
      config: {
        rows: [
          {
            id: "r_stats",
            kind: "row",
            height: "sm",
            cells: [
              {
                id: "w_orders",
                kind: "stat",
                title: "Orders",
                icon: "ti ti-shopping-cart",
                format: "integer",
                source: { tableId: table("orders"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
              {
                id: "w_revenue",
                kind: "stat",
                title: "Revenue",
                icon: "ti ti-currency-euro",
                format: "currency",
                source: { tableId: table("orders"), aggregations: [{ fieldId: field("orders.line_total"), agg: "sum" }] },
              },
              {
                id: "w_books",
                kind: "stat",
                title: "Books",
                icon: "ti ti-books",
                format: "integer",
                source: { tableId: table("books"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
            ],
          },
          {
            id: "r_main",
            kind: "row",
            height: "md",
            cells: [
              {
                id: "w_chart",
                kind: "chart",
                title: "Orders by month",
                chartType: "bar",
                viewId: view("orders_by_month"),
                format: "currency",
              },
              { id: "w_form", kind: "form", title: "Newsletter", formId: form("newsletter") },
            ],
          },
          {
            id: "r_views",
            kind: "row",
            height: "md",
            cells: [
              { id: "w_recent", kind: "view", title: "Recent books", source: { kind: "view", viewId: view("recent_books") } },
              { id: "w_author_stats", kind: "view-stats", title: "Books per author", viewId: view("books_per_author") },
            ],
          },
        ],
      },
    },
  ],
  defaultDashboard: "sales",
};
