import { field, form, type GridTemplate, record, table, view } from "./types";

export const contentTemplate: GridTemplate = {
  id: "content",
  name: "Content calendar",
  description: "Campaigns, authors, channels, content pieces, editorial pipeline, idea intake, and publishing dashboards.",
  icon: "ti ti-news",
  baseName: "Content Calendar",
  baseDescription: "Editorial planning for posts, newsletters, launches, and campaigns.",
  tables: [
    {
      key: "authors",
      name: "Authors",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-user" },
        { key: "email", name: "email", type: "text", config: { regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" }, icon: "ti ti-mail" },
        { key: "role", name: "role", type: "text", icon: "ti ti-id-badge" },
      ],
    },
    {
      key: "channels",
      name: "Channels",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-speakerphone" },
        {
          key: "kind",
          name: "kind",
          type: "select",
          icon: "ti ti-category",
          config: {
            options: [
              { id: "blog", label: "Blog", color: "#3b82f6" },
              { id: "newsletter", label: "Newsletter", color: "#22c55e" },
              { id: "social", label: "Social", color: "#a855f7" },
              { id: "webinar", label: "Webinar", color: "#f59e0b" },
            ],
          },
        },
      ],
    },
    {
      key: "campaigns",
      name: "Campaigns",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-flag" },
        { key: "owner", name: "owner", type: "text", icon: "ti ti-user-check" },
        { key: "start_date", name: "start_date", type: "date", icon: "ti ti-calendar" },
        { key: "end_date", name: "end_date", type: "date", icon: "ti ti-calendar-due" },
        { key: "goal", name: "goal", type: "longtext", icon: "ti ti-target" },
      ],
    },
    {
      key: "pieces",
      name: "Content",
      fields: [
        { key: "title", name: "title", type: "text", required: true, presentable: true, icon: "ti ti-heading" },
        { key: "body", name: "body", type: "longtext", icon: "ti ti-markdown" },
        {
          key: "author",
          name: "author",
          type: "relation",
          icon: "ti ti-user",
          config: { targetTableId: table("authors"), cardinality: "single" },
        },
        {
          key: "channel",
          name: "channel",
          type: "relation",
          icon: "ti ti-speakerphone",
          config: { targetTableId: table("channels"), cardinality: "single" },
        },
        {
          key: "campaign",
          name: "campaign",
          type: "relation",
          icon: "ti ti-flag",
          config: { targetTableId: table("campaigns"), cardinality: "single" },
        },
        {
          key: "channel_name",
          name: "channel_name",
          type: "lookup",
          icon: "ti ti-hierarchy",
          config: { relationFieldId: field("pieces.channel"), targetFieldId: field("channels.name") },
        },
        {
          key: "status",
          name: "status",
          type: "select",
          icon: "ti ti-progress",
          config: {
            options: [
              { id: "idea", label: "Idea", color: "#94a3b8" },
              { id: "draft", label: "Draft", color: "#64748b" },
              { id: "review", label: "Review", color: "#f59e0b" },
              { id: "scheduled", label: "Scheduled", color: "#3b82f6" },
              { id: "published", label: "Published", color: "#22c55e" },
            ],
          },
        },
        {
          key: "content_type",
          name: "content_type",
          type: "select",
          icon: "ti ti-file-text",
          config: {
            options: [
              { id: "article", label: "Article", color: "#3b82f6" },
              { id: "email", label: "Email", color: "#22c55e" },
              { id: "post", label: "Social post", color: "#a855f7" },
              { id: "webinar", label: "Webinar", color: "#f59e0b" },
            ],
          },
        },
        { key: "publish_date", name: "publish_date", type: "date", icon: "ti ti-calendar" },
        { key: "effort_hours", name: "effort_hours", type: "number", config: { min: 0 }, icon: "ti ti-clock" },
        {
          key: "tags",
          name: "tags",
          type: "select",
          icon: "ti ti-tags",
          config: {
            multiple: true,
            options: [
              { id: "product", label: "Product", color: "#3b82f6" },
              { id: "company", label: "Company", color: "#22c55e" },
              { id: "guide", label: "Guide", color: "#f59e0b" },
              { id: "launch", label: "Launch", color: "#ef4444" },
            ],
          },
        },
      ],
    },
  ],
  records: [
    { key: "authors.eva", table: "authors", values: { name: "Eva Hoffmann", email: "eva@example.com", role: "Editor" } },
    { key: "authors.dan", table: "authors", values: { name: "Dan Fischer", email: "dan@example.com", role: "Product writer" } },
    { key: "authors.mira", table: "authors", values: { name: "Mira Becker", email: "mira@example.com", role: "Community" } },
    { key: "channels.blog", table: "channels", values: { name: "Blog", kind: ["blog"] } },
    { key: "channels.newsletter", table: "channels", values: { name: "Newsletter", kind: ["newsletter"] } },
    { key: "channels.linkedin", table: "channels", values: { name: "LinkedIn", kind: ["social"] } },
    { key: "channels.webinar", table: "channels", values: { name: "Webinar", kind: ["webinar"] } },
    {
      key: "campaigns.launch",
      table: "campaigns",
      values: {
        name: "Spring launch",
        owner: "Eva",
        start_date: "2026-05-01",
        end_date: "2026-06-15",
        goal: "Explain the new dashboard workflow and drive trials.",
      },
    },
    {
      key: "campaigns.education",
      table: "campaigns",
      values: {
        name: "Education series",
        owner: "Dan",
        start_date: "2026-05-10",
        end_date: "2026-07-01",
        goal: "Evergreen product education.",
      },
    },
    {
      key: "pieces.launch_notes",
      table: "pieces",
      values: {
        title: "Launch notes",
        body: "## Highlights\n\n- Faster imports\n- Better dashboards",
        author: [record("authors.eva")],
        channel: [record("channels.blog")],
        campaign: [record("campaigns.launch")],
        status: ["scheduled"],
        content_type: ["article"],
        publish_date: "2026-05-27",
        effort_hours: 5,
        tags: ["product", "launch"],
      },
    },
    {
      key: "pieces.roundup",
      table: "pieces",
      values: {
        title: "May roundup",
        author: [record("authors.dan")],
        channel: [record("channels.newsletter")],
        campaign: [record("campaigns.launch")],
        status: ["draft"],
        content_type: ["email"],
        publish_date: "2026-05-31",
        effort_hours: 3,
        tags: ["company"],
      },
    },
    {
      key: "pieces.dashboard_guide",
      table: "pieces",
      values: {
        title: "How to read a dashboard",
        author: [record("authors.dan")],
        channel: [record("channels.blog")],
        campaign: [record("campaigns.education")],
        status: ["review"],
        content_type: ["article"],
        publish_date: "2026-06-03",
        effort_hours: 8,
        tags: ["guide", "product"],
      },
    },
    {
      key: "pieces.webinar",
      table: "pieces",
      values: {
        title: "Live dashboard walkthrough",
        author: [record("authors.eva")],
        channel: [record("channels.webinar")],
        campaign: [record("campaigns.education")],
        status: ["scheduled"],
        content_type: ["webinar"],
        publish_date: "2026-06-12",
        effort_hours: 12,
        tags: ["guide"],
      },
    },
    {
      key: "pieces.linkedin_teaser",
      table: "pieces",
      values: {
        title: "Dashboard teaser",
        author: [record("authors.mira")],
        channel: [record("channels.linkedin")],
        campaign: [record("campaigns.launch")],
        status: ["published"],
        content_type: ["post"],
        publish_date: "2026-05-08",
        effort_hours: 1,
        tags: ["launch"],
      },
    },
    {
      key: "pieces.case_study",
      table: "pieces",
      values: {
        title: "Customer story outline",
        author: [record("authors.eva")],
        channel: [record("channels.blog")],
        campaign: [record("campaigns.education")],
        status: ["idea"],
        content_type: ["article"],
        publish_date: "2026-06-20",
        effort_hours: 6,
        tags: ["company"],
      },
    },
  ],
  views: [
    {
      key: "calendar",
      table: "pieces",
      name: "Upcoming content",
      shared: true,
      query: {
        sort: [{ fieldId: field("pieces.publish_date"), direction: "asc" }],
        columns: [
          { fieldId: field("pieces.title") },
          { fieldId: field("pieces.channel") },
          { fieldId: field("pieces.campaign") },
          { fieldId: field("pieces.status") },
          { fieldId: field("pieces.publish_date") },
        ],
      },
    },
    {
      key: "by_channel",
      table: "pieces",
      name: "Content by channel",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("pieces.channel") }],
        aggregations: [
          { fieldId: "*", agg: "count", label: "pieces" },
          { fieldId: field("pieces.effort_hours"), agg: "sum", label: "hours" },
        ],
      },
    },
    {
      key: "by_status",
      table: "pieces",
      name: "Pipeline by status",
      shared: true,
      query: { groupBy: [{ fieldId: field("pieces.status") }], aggregations: [{ fieldId: "*", agg: "count", label: "pieces" }] },
    },
    {
      key: "published_by_month",
      table: "pieces",
      name: "Published by month",
      shared: true,
      query: {
        filter: { op: "is", fieldId: field("pieces.status"), value: "published" },
        groupBy: [{ fieldId: field("pieces.publish_date"), granularity: "month" }],
        aggregations: [{ fieldId: "*", agg: "count", label: "published" }],
      },
    },
    {
      key: "campaign_workload",
      table: "pieces",
      name: "Campaign workload",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("pieces.campaign") }],
        aggregations: [
          { fieldId: "*", agg: "count", label: "pieces" },
          { fieldId: field("pieces.effort_hours"), agg: "sum", label: "hours" },
        ],
      },
    },
  ],
  forms: [
    {
      key: "idea_intake",
      table: "pieces",
      name: "Content idea",
      config: {
        title: "Submit content idea",
        submitLabel: "Add idea",
        fields: [
          { kind: "user_input", fieldId: field("pieces.title"), label: "Title", required: true },
          { kind: "user_input", fieldId: field("pieces.body"), label: "Notes" },
          { kind: "user_input", fieldId: field("pieces.author"), label: "Owner" },
          { kind: "user_input", fieldId: field("pieces.channel"), label: "Channel" },
          { kind: "user_input", fieldId: field("pieces.campaign"), label: "Campaign" },
          { kind: "user_input", fieldId: field("pieces.publish_date"), label: "Target date" },
          { kind: "form_value", fieldId: field("pieces.status"), value: ["idea"] },
        ],
      },
    },
  ],
  dashboards: [
    {
      key: "overview",
      name: "Editorial overview",
      description: "Editorial pipeline, upcoming work, campaign workload, and idea intake.",
      shared: true,
      config: {
        rows: [
          {
            id: "r_stats",
            kind: "row",
            height: "sm",
            cells: [
              {
                id: "w_total",
                kind: "stat",
                title: "Pieces",
                icon: "ti ti-news",
                format: "integer",
                source: { tableId: table("pieces"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
              {
                id: "w_hours",
                kind: "stat",
                title: "Planned hours",
                icon: "ti ti-clock",
                format: "integer",
                source: { tableId: table("pieces"), aggregations: [{ fieldId: field("pieces.effort_hours"), agg: "sum" }] },
              },
              {
                id: "w_campaigns",
                kind: "stat",
                title: "Campaigns",
                icon: "ti ti-flag",
                format: "integer",
                source: { tableId: table("campaigns"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
            ],
          },
          {
            id: "r_charts",
            kind: "row",
            height: "md",
            cells: [
              { id: "w_status", kind: "chart", title: "Pipeline by status", chartType: "donut", viewId: view("by_status") },
              {
                id: "w_channel",
                kind: "chart",
                title: "Content by channel",
                chartType: "bar",
                viewId: view("by_channel"),
                format: "integer",
              },
            ],
          },
          {
            id: "r_work",
            kind: "row",
            height: "lg",
            cells: [
              { id: "w_calendar", kind: "view", title: "Upcoming content", source: { kind: "view", viewId: view("calendar") } },
              { id: "w_form", kind: "form", title: "Add idea", formId: form("idea_intake") },
            ],
          },
          {
            id: "r_campaigns",
            kind: "row",
            height: "md",
            cells: [
              {
                id: "w_campaign_workload",
                kind: "chart",
                title: "Campaign workload",
                chartType: "bar",
                viewId: view("campaign_workload"),
                format: "integer",
              },
              {
                id: "w_published",
                kind: "chart",
                title: "Published by month",
                chartType: "bar",
                viewId: view("published_by_month"),
                format: "integer",
              },
            ],
          },
        ],
      },
    },
  ],
  defaultDashboard: "overview",
};
