import { field, form, type GridTemplate, record, table, view } from "./types";

export const crmTemplate: GridTemplate = {
  id: "crm",
  name: "CRM pipeline",
  description: "Companies, contacts, deals, sales activities, pipeline dashboards, and quick follow-up logging.",
  icon: "ti ti-users",
  baseName: "CRM",
  baseDescription: "Simple sales CRM for accounts, contacts, deals, and follow-ups.",
  tables: [
    {
      key: "companies",
      name: "Companies",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-building" },
        { key: "website", name: "website", type: "text", config: { regex: "^https?://.+" }, icon: "ti ti-world" },
        {
          key: "industry",
          name: "industry",
          type: "select",
          icon: "ti ti-briefcase",
          config: {
            options: [
              { id: "saas", label: "SaaS", color: "#3b82f6" },
              { id: "retail", label: "Retail", color: "#22c55e" },
              { id: "services", label: "Services", color: "#a855f7" },
              { id: "manufacturing", label: "Manufacturing", color: "#f59e0b" },
            ],
          },
        },
        {
          key: "status",
          name: "status",
          type: "select",
          icon: "ti ti-progress",
          config: {
            options: [
              { id: "lead", label: "Lead", color: "#94a3b8" },
              { id: "active", label: "Active", color: "#22c55e" },
              { id: "customer", label: "Customer", color: "#3b82f6" },
            ],
          },
        },
        { key: "employees", name: "employees", type: "number", config: { min: 1, integerOnly: true }, icon: "ti ti-users" },
        { key: "notes", name: "notes", type: "longtext", icon: "ti ti-notes" },
      ],
    },
    {
      key: "contacts",
      name: "Contacts",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-user" },
        { key: "email", name: "email", type: "text", config: { regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" }, icon: "ti ti-mail" },
        { key: "phone", name: "phone", type: "text", icon: "ti ti-phone" },
        { key: "role", name: "role", type: "text", icon: "ti ti-id-badge" },
        {
          key: "company",
          name: "company",
          type: "relation",
          icon: "ti ti-building",
          config: { targetTableId: table("companies"), cardinality: "single" },
        },
        {
          key: "company_name",
          name: "company_name",
          type: "lookup",
          icon: "ti ti-hierarchy",
          config: { relationFieldId: field("contacts.company"), targetFieldId: field("companies.name") },
        },
        { key: "last_touch", name: "last_touch", type: "date", icon: "ti ti-calendar" },
      ],
    },
    {
      key: "deals",
      name: "Deals",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-target-arrow" },
        {
          key: "company",
          name: "company",
          type: "relation",
          icon: "ti ti-building",
          config: { targetTableId: table("companies"), cardinality: "single" },
        },
        {
          key: "primary_contact",
          name: "primary_contact",
          type: "relation",
          icon: "ti ti-user",
          config: { targetTableId: table("contacts"), cardinality: "single" },
        },
        { key: "owner", name: "owner", type: "text", icon: "ti ti-user-check" },
        {
          key: "value",
          name: "value",
          type: "decimal",
          icon: "ti ti-currency-euro",
          config: { precision: 16, scale: 2, unit: "EUR", unitPosition: "suffix" },
        },
        {
          key: "stage",
          name: "stage",
          type: "select",
          icon: "ti ti-layers-linked",
          config: {
            options: [
              { id: "lead", label: "Lead", color: "#94a3b8" },
              { id: "qualified", label: "Qualified", color: "#3b82f6" },
              { id: "proposal", label: "Proposal", color: "#f59e0b" },
              { id: "negotiation", label: "Negotiation", color: "#a855f7" },
              { id: "won", label: "Won", color: "#22c55e" },
              { id: "lost", label: "Lost", color: "#ef4444" },
            ],
          },
        },
        {
          key: "probability",
          name: "probability",
          type: "number",
          config: { min: 0, max: 100, integerOnly: true },
          icon: "ti ti-percentage",
        },
        { key: "close_date", name: "close_date", type: "date", icon: "ti ti-calendar" },
        { key: "next_step", name: "next_step", type: "longtext", icon: "ti ti-list-check" },
      ],
    },
    {
      key: "activities",
      name: "Activities",
      fields: [
        { key: "summary", name: "summary", type: "text", required: true, presentable: true, icon: "ti ti-message" },
        {
          key: "contact",
          name: "contact",
          type: "relation",
          icon: "ti ti-user",
          config: { targetTableId: table("contacts"), cardinality: "single" },
        },
        {
          key: "deal",
          name: "deal",
          type: "relation",
          icon: "ti ti-target-arrow",
          config: { targetTableId: table("deals"), cardinality: "single" },
        },
        {
          key: "kind",
          name: "kind",
          type: "select",
          icon: "ti ti-phone-call",
          config: {
            options: [
              { id: "call", label: "Call", color: "#3b82f6" },
              { id: "email", label: "Email", color: "#22c55e" },
              { id: "meeting", label: "Meeting", color: "#a855f7" },
              { id: "demo", label: "Demo", color: "#f59e0b" },
            ],
          },
        },
        { key: "due_at", name: "due_at", type: "date", icon: "ti ti-calendar-due" },
        { key: "done", name: "done", type: "boolean", defaultValue: false, icon: "ti ti-check" },
        { key: "notes", name: "notes", type: "longtext", icon: "ti ti-notes" },
      ],
    },
  ],
  records: [
    {
      key: "companies.acme",
      table: "companies",
      values: {
        name: "Acme GmbH",
        website: "https://acme.example",
        industry: ["saas"],
        status: ["active"],
        employees: 180,
        notes: "Security review is important.",
      },
    },
    {
      key: "companies.nova",
      table: "companies",
      values: { name: "Nova Retail", website: "https://nova.example", industry: ["retail"], status: ["lead"], employees: 75 },
    },
    {
      key: "companies.orbit",
      table: "companies",
      values: { name: "Orbit Services", website: "https://orbit.example", industry: ["services"], status: ["customer"], employees: 42 },
    },
    {
      key: "companies.fabrik",
      table: "companies",
      values: { name: "Fabrik AG", website: "https://fabrik.example", industry: ["manufacturing"], status: ["active"], employees: 320 },
    },
    {
      key: "contacts.anna",
      table: "contacts",
      values: {
        name: "Anna Weber",
        email: "anna@acme.example",
        phone: "+49 30 123456",
        role: "Head of IT",
        company: [record("companies.acme")],
        last_touch: "2026-05-10",
      },
    },
    {
      key: "contacts.tom",
      table: "contacts",
      values: {
        name: "Tom Berger",
        email: "tom@acme.example",
        role: "Procurement",
        company: [record("companies.acme")],
        last_touch: "2026-05-03",
      },
    },
    {
      key: "contacts.max",
      table: "contacts",
      values: {
        name: "Max Keller",
        email: "max@nova.example",
        role: "Operations",
        company: [record("companies.nova")],
        last_touch: "2026-05-12",
      },
    },
    {
      key: "contacts.mira",
      table: "contacts",
      values: {
        name: "Mira Schmid",
        email: "mira@orbit.example",
        role: "Founder",
        company: [record("companies.orbit")],
        last_touch: "2026-04-28",
      },
    },
    {
      key: "contacts.klara",
      table: "contacts",
      values: {
        name: "Klara Vogt",
        email: "klara@fabrik.example",
        role: "CFO",
        company: [record("companies.fabrik")],
        last_touch: "2026-05-07",
      },
    },
    {
      key: "deals.acme",
      table: "deals",
      values: {
        name: "Acme rollout",
        company: [record("companies.acme")],
        primary_contact: [record("contacts.anna")],
        owner: "Valentin",
        value: "12000.00",
        stage: ["proposal"],
        probability: 65,
        close_date: "2026-06-30",
        next_step: "Send updated security answers.",
      },
    },
    {
      key: "deals.nova",
      table: "deals",
      values: {
        name: "Nova pilot",
        company: [record("companies.nova")],
        primary_contact: [record("contacts.max")],
        owner: "Kochi",
        value: "4500.00",
        stage: ["qualified"],
        probability: 40,
        close_date: "2026-05-30",
        next_step: "Schedule workflow demo.",
      },
    },
    {
      key: "deals.orbit",
      table: "deals",
      values: {
        name: "Orbit renewal",
        company: [record("companies.orbit")],
        primary_contact: [record("contacts.mira")],
        owner: "Valentin",
        value: "7800.00",
        stage: ["won"],
        probability: 100,
        close_date: "2026-04-25",
      },
    },
    {
      key: "deals.fabrik",
      table: "deals",
      values: {
        name: "Fabrik compliance package",
        company: [record("companies.fabrik")],
        primary_contact: [record("contacts.klara")],
        owner: "Mara",
        value: "21500.00",
        stage: ["negotiation"],
        probability: 75,
        close_date: "2026-07-15",
        next_step: "Discuss payment terms.",
      },
    },
    {
      key: "deals.acme_training",
      table: "deals",
      values: {
        name: "Acme training",
        company: [record("companies.acme")],
        primary_contact: [record("contacts.tom")],
        owner: "Kochi",
        value: "2600.00",
        stage: ["lead"],
        probability: 20,
        close_date: "2026-08-01",
      },
    },
    {
      key: "activities.acme_call",
      table: "activities",
      values: {
        summary: "Review security questions",
        contact: [record("contacts.anna")],
        deal: [record("deals.acme")],
        kind: ["call"],
        due_at: "2026-05-20",
        done: false,
        notes: "Focus on data retention.",
      },
    },
    {
      key: "activities.nova_demo",
      table: "activities",
      values: {
        summary: "Workflow demo",
        contact: [record("contacts.max")],
        deal: [record("deals.nova")],
        kind: ["demo"],
        due_at: "2026-05-22",
        done: false,
      },
    },
    {
      key: "activities.orbit_checkin",
      table: "activities",
      values: {
        summary: "Renewal check-in",
        contact: [record("contacts.mira")],
        deal: [record("deals.orbit")],
        kind: ["email"],
        due_at: "2026-04-20",
        done: true,
      },
    },
    {
      key: "activities.fabrik_terms",
      table: "activities",
      values: {
        summary: "Payment terms meeting",
        contact: [record("contacts.klara")],
        deal: [record("deals.fabrik")],
        kind: ["meeting"],
        due_at: "2026-05-24",
        done: false,
      },
    },
    {
      key: "activities.acme_training",
      table: "activities",
      values: {
        summary: "Qualify training need",
        contact: [record("contacts.tom")],
        deal: [record("deals.acme_training")],
        kind: ["call"],
        due_at: "2026-05-27",
        done: false,
      },
    },
  ],
  views: [
    {
      key: "pipeline",
      table: "deals",
      name: "Pipeline by stage",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("deals.stage") }],
        aggregations: [
          { fieldId: "*", agg: "count", label: "deals" },
          { fieldId: field("deals.value"), agg: "sum", label: "value" },
        ],
        groupSort: [{ fieldId: field("deals.value"), agg: "sum", direction: "desc" }],
      },
    },
    {
      key: "forecast",
      table: "deals",
      name: "Forecast by close month",
      shared: true,
      query: {
        groupBy: [{ fieldId: field("deals.close_date"), granularity: "month" }],
        aggregations: [
          { fieldId: field("deals.value"), agg: "sum", label: "value" },
          { fieldId: "*", agg: "count", label: "deals" },
        ],
      },
    },
    {
      key: "won_revenue",
      table: "deals",
      name: "Won revenue",
      shared: true,
      query: {
        filter: { op: "is", fieldId: field("deals.stage"), value: "won" },
        groupBy: [{ fieldId: field("deals.close_date"), granularity: "month" }],
        aggregations: [{ fieldId: field("deals.value"), agg: "sum", label: "won" }],
      },
    },
    {
      key: "open_activities",
      table: "activities",
      name: "Open activities",
      shared: true,
      query: {
        filter: { op: "=", fieldId: field("activities.done"), value: false },
        sort: [{ fieldId: field("activities.due_at"), direction: "asc" }],
        columns: [
          { fieldId: field("activities.summary") },
          { fieldId: field("activities.contact") },
          { fieldId: field("activities.deal") },
          { fieldId: field("activities.kind") },
          { fieldId: field("activities.due_at") },
        ],
      },
    },
    {
      key: "closing_soon",
      table: "deals",
      name: "Closing soon",
      shared: true,
      query: {
        sort: [{ fieldId: field("deals.close_date"), direction: "asc" }],
        columns: [
          { fieldId: field("deals.name") },
          { fieldId: field("deals.company") },
          { fieldId: field("deals.stage") },
          { fieldId: field("deals.value") },
          { fieldId: field("deals.close_date") },
        ],
        limit: 10,
      },
    },
  ],
  forms: [
    {
      key: "log_activity",
      table: "activities",
      name: "Log activity",
      config: {
        title: "Log activity",
        submitLabel: "Add activity",
        fields: [
          { kind: "user_input", fieldId: field("activities.summary"), label: "Summary", required: true },
          { kind: "user_input", fieldId: field("activities.contact"), label: "Contact" },
          { kind: "user_input", fieldId: field("activities.deal"), label: "Deal" },
          { kind: "user_input", fieldId: field("activities.kind"), label: "Kind", required: true },
          { kind: "user_input", fieldId: field("activities.due_at"), label: "Due date" },
          { kind: "user_input", fieldId: field("activities.notes"), label: "Notes" },
          { kind: "form_value", fieldId: field("activities.done"), value: false },
        ],
      },
    },
  ],
  dashboards: [
    {
      key: "overview",
      name: "CRM overview",
      description: "Pipeline health, forecast, open tasks, and activity logging.",
      shared: true,
      config: {
        rows: [
          {
            id: "r_stats",
            kind: "row",
            height: "sm",
            cells: [
              {
                id: "w_pipeline",
                kind: "stat",
                title: "Pipeline",
                icon: "ti ti-currency-euro",
                format: "currency",
                source: { tableId: table("deals"), aggregations: [{ fieldId: field("deals.value"), agg: "sum" }] },
              },
              {
                id: "w_won",
                kind: "stat",
                title: "Won",
                icon: "ti ti-trophy",
                format: "currency",
                source: {
                  tableId: table("deals"),
                  filter: { op: "is", fieldId: field("deals.stage"), value: "won" },
                  aggregations: [{ fieldId: field("deals.value"), agg: "sum" }],
                },
              },
              {
                id: "w_companies",
                kind: "stat",
                title: "Companies",
                icon: "ti ti-building",
                format: "integer",
                source: { tableId: table("companies"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
              {
                id: "w_open",
                kind: "stat",
                title: "Open activities",
                icon: "ti ti-list-check",
                format: "integer",
                source: {
                  tableId: table("activities"),
                  filter: { op: "=", fieldId: field("activities.done"), value: false },
                  aggregations: [{ fieldId: "*", agg: "count" }],
                },
              },
            ],
          },
          {
            id: "r_charts",
            kind: "row",
            height: "md",
            cells: [
              { id: "w_stage", kind: "chart", title: "Pipeline by stage", chartType: "bar", viewId: view("pipeline"), format: "currency" },
              {
                id: "w_forecast",
                kind: "chart",
                title: "Forecast by month",
                chartType: "bar",
                viewId: view("forecast"),
                format: "currency",
              },
            ],
          },
          {
            id: "r_work",
            kind: "row",
            height: "lg",
            cells: [
              { id: "w_activities", kind: "view", title: "Open activities", source: { kind: "view", viewId: view("open_activities") } },
              { id: "w_form", kind: "form", title: "Log activity", formId: form("log_activity") },
            ],
          },
          {
            id: "r_deals",
            kind: "row",
            height: "md",
            cells: [
              { id: "w_closing", kind: "view", title: "Closing soon", source: { kind: "view", viewId: view("closing_soon") } },
              { id: "w_won_chart", kind: "chart", title: "Won revenue", chartType: "bar", viewId: view("won_revenue"), format: "currency" },
            ],
          },
        ],
      },
    },
  ],
  defaultDashboard: "overview",
};
