import { field, form, type GridTemplate, record, table, view } from "./types";

export const financeTemplate: GridTemplate = {
  id: "finance",
  name: "Personal finance",
  description: "Accounts, merchants, categories, transactions, budgets, spending charts, and quick expense logging.",
  icon: "ti ti-wallet",
  baseName: "Personal Finance",
  baseDescription: "Track personal spending, income, budgets, and recent purchases.",
  tables: [
    {
      key: "accounts",
      name: "Accounts",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-credit-card" },
        {
          key: "kind",
          name: "kind",
          type: "select",
          icon: "ti ti-category",
          config: {
            options: [
              { id: "checking", label: "Checking", color: "#3b82f6" },
              { id: "cash", label: "Cash", color: "#22c55e" },
              { id: "savings", label: "Savings", color: "#a855f7" },
              { id: "credit", label: "Credit card", color: "#f59e0b" },
            ],
          },
        },
        {
          key: "opening_balance",
          name: "opening_balance",
          type: "number",
          icon: "ti ti-currency-euro",
          config: { precision: 16, decimalPlaces: 2, unit: "EUR", unitPosition: "suffix" },
        },
      ],
    },
    {
      key: "categories",
      name: "Categories",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-tag" },
        {
          key: "kind",
          name: "kind",
          type: "select",
          icon: "ti ti-arrows-exchange",
          config: {
            options: [
              { id: "income", label: "Income", color: "#22c55e" },
              { id: "expense", label: "Expense", color: "#ef4444" },
            ],
          },
        },
        { key: "fixed", name: "fixed", type: "boolean", icon: "ti ti-lock", defaultValue: false },
      ],
    },
    {
      key: "merchants",
      name: "Merchants",
      fields: [
        { key: "name", name: "name", type: "text", required: true, presentable: true, icon: "ti ti-building-store" },
        {
          key: "default_category",
          name: "default_category",
          type: "relation",
          icon: "ti ti-tag",
          config: { targetTableId: table("categories"), cardinality: "single" },
        },
        { key: "website", name: "website", type: "text", config: { regex: "^https?://.+" }, icon: "ti ti-world" },
      ],
    },
    {
      key: "transactions",
      name: "Transactions",
      fields: [
        {
          key: "transaction_ref",
          name: "transaction_ref",
          description: "Generated monthly reference for this transaction.",
          type: "id",
          config: { strategy: "date_sequence", prefix: "TX-", period: "month", padding: 4 },
          icon: "ti ti-id",
        },
        { key: "date", name: "date", type: "date", icon: "ti ti-calendar" },
        {
          key: "merchant",
          name: "merchant",
          type: "relation",
          icon: "ti ti-building-store",
          config: { targetTableId: table("merchants"), cardinality: "single" },
        },
        {
          key: "account",
          name: "account",
          type: "relation",
          icon: "ti ti-credit-card",
          config: { targetTableId: table("accounts"), cardinality: "single" },
        },
        {
          key: "category",
          name: "category",
          type: "relation",
          icon: "ti ti-tag",
          config: { targetTableId: table("categories"), cardinality: "single" },
        },
        {
          key: "merchant_name",
          name: "merchant_name",
          type: "lookup",
          icon: "ti ti-hierarchy",
          config: { relationFieldId: field("transactions.merchant"), targetFieldId: field("merchants.name") },
        },
        {
          key: "merchant_website",
          name: "merchant_website",
          type: "lookup",
          icon: "ti ti-qrcode",
          config: { relationFieldId: field("transactions.merchant"), targetFieldId: field("merchants.website") },
        },
        {
          key: "category_name",
          name: "category_name",
          type: "lookup",
          icon: "ti ti-hierarchy",
          config: { relationFieldId: field("transactions.category"), targetFieldId: field("categories.name") },
        },
        {
          key: "type",
          name: "type",
          type: "select",
          icon: "ti ti-arrows-exchange",
          config: {
            options: [
              { id: "expense", label: "Expense", color: "#ef4444" },
              { id: "income", label: "Income", color: "#22c55e" },
              { id: "transfer", label: "Transfer", color: "#94a3b8" },
            ],
          },
        },
        {
          key: "amount",
          name: "amount",
          type: "number",
          icon: "ti ti-currency-euro",
          config: { precision: 16, decimalPlaces: 2, min: "0", unit: "EUR", unitPosition: "suffix" },
        },
        { key: "cleared", name: "cleared", type: "boolean", icon: "ti ti-circle-check", defaultValue: true },
        { key: "notes", name: "notes", type: "longtext", icon: "ti ti-notes" },
      ],
    },
    {
      key: "budgets",
      name: "Budgets",
      fields: [
        { key: "month", name: "month", type: "date", required: true, presentable: true, icon: "ti ti-calendar-month" },
        {
          key: "category",
          name: "category",
          type: "relation",
          icon: "ti ti-tag",
          config: { targetTableId: table("categories"), cardinality: "single" },
        },
        {
          key: "limit",
          name: "limit",
          type: "number",
          icon: "ti ti-currency-euro",
          config: { precision: 16, decimalPlaces: 2, unit: "EUR", unitPosition: "suffix" },
        },
      ],
    },
  ],
  records: [
    { key: "accounts.main", table: "accounts", values: { name: "Main account", kind: ["checking"], opening_balance: "2450.00" } },
    { key: "accounts.savings", table: "accounts", values: { name: "Savings", kind: ["savings"], opening_balance: "8400.00" } },
    { key: "accounts.cash", table: "accounts", values: { name: "Cash", kind: ["cash"], opening_balance: "120.00" } },
    { key: "accounts.card", table: "accounts", values: { name: "Visa", kind: ["credit"], opening_balance: "0.00" } },
    { key: "categories.salary", table: "categories", values: { name: "Salary", kind: ["income"], fixed: true } },
    { key: "categories.groceries", table: "categories", values: { name: "Groceries", kind: ["expense"], fixed: false } },
    { key: "categories.rent", table: "categories", values: { name: "Rent", kind: ["expense"], fixed: true } },
    { key: "categories.transport", table: "categories", values: { name: "Transport", kind: ["expense"], fixed: false } },
    { key: "categories.books", table: "categories", values: { name: "Books", kind: ["expense"], fixed: false } },
    { key: "categories.food", table: "categories", values: { name: "Food & coffee", kind: ["expense"], fixed: false } },
    { key: "categories.utilities", table: "categories", values: { name: "Utilities", kind: ["expense"], fixed: true } },
    {
      key: "merchants.employer",
      table: "merchants",
      values: { name: "Employer GmbH", default_category: [record("categories.salary")], website: "https://employer.example" },
    },
    {
      key: "merchants.landlord",
      table: "merchants",
      values: { name: "Landlord", default_category: [record("categories.rent")], website: "https://rent.example" },
    },
    {
      key: "merchants.market",
      table: "merchants",
      values: { name: "Local Market", default_category: [record("categories.groceries")], website: "https://market.example" },
    },
    {
      key: "merchants.transit",
      table: "merchants",
      values: { name: "City Transit", default_category: [record("categories.transport")], website: "https://transit.example" },
    },
    {
      key: "merchants.bookshop",
      table: "merchants",
      values: { name: "Bookshop", default_category: [record("categories.books")], website: "https://bookshop.example" },
    },
    {
      key: "merchants.cafe",
      table: "merchants",
      values: { name: "Corner Cafe", default_category: [record("categories.food")], website: "https://cafe.example" },
    },
    {
      key: "merchants.power",
      table: "merchants",
      values: { name: "Power Utility", default_category: [record("categories.utilities")], website: "https://power.example" },
    },
    {
      key: "transactions.salary_apr",
      table: "transactions",
      values: {
        date: "2026-04-01",
        merchant: [record("merchants.employer")],
        account: [record("accounts.main")],
        category: [record("categories.salary")],
        type: ["income"],
        amount: "3200.00",
        cleared: true,
      },
    },
    {
      key: "transactions.rent_apr",
      table: "transactions",
      values: {
        date: "2026-04-02",
        merchant: [record("merchants.landlord")],
        account: [record("accounts.main")],
        category: [record("categories.rent")],
        type: ["expense"],
        amount: "980.00",
        cleared: true,
      },
    },
    {
      key: "transactions.market_apr",
      table: "transactions",
      values: {
        date: "2026-04-05",
        merchant: [record("merchants.market")],
        account: [record("accounts.card")],
        category: [record("categories.groceries")],
        type: ["expense"],
        amount: "76.40",
        cleared: true,
      },
    },
    {
      key: "transactions.cafe_apr",
      table: "transactions",
      values: {
        date: "2026-04-09",
        merchant: [record("merchants.cafe")],
        account: [record("accounts.card")],
        category: [record("categories.food")],
        type: ["expense"],
        amount: "14.80",
        cleared: true,
      },
    },
    {
      key: "transactions.books_apr",
      table: "transactions",
      values: {
        date: "2026-04-18",
        merchant: [record("merchants.bookshop")],
        account: [record("accounts.cash")],
        category: [record("categories.books")],
        type: ["expense"],
        amount: "28.90",
        cleared: true,
      },
    },
    {
      key: "transactions.salary_may",
      table: "transactions",
      values: {
        date: "2026-05-01",
        merchant: [record("merchants.employer")],
        account: [record("accounts.main")],
        category: [record("categories.salary")],
        type: ["income"],
        amount: "3200.00",
        cleared: true,
      },
    },
    {
      key: "transactions.rent_may",
      table: "transactions",
      values: {
        date: "2026-05-02",
        merchant: [record("merchants.landlord")],
        account: [record("accounts.main")],
        category: [record("categories.rent")],
        type: ["expense"],
        amount: "980.00",
        cleared: true,
      },
    },
    {
      key: "transactions.power_may",
      table: "transactions",
      values: {
        date: "2026-05-03",
        merchant: [record("merchants.power")],
        account: [record("accounts.main")],
        category: [record("categories.utilities")],
        type: ["expense"],
        amount: "92.30",
        cleared: true,
      },
    },
    {
      key: "transactions.market_may_1",
      table: "transactions",
      values: {
        date: "2026-05-04",
        merchant: [record("merchants.market")],
        account: [record("accounts.card")],
        category: [record("categories.groceries")],
        type: ["expense"],
        amount: "82.40",
        cleared: true,
      },
    },
    {
      key: "transactions.transit_may",
      table: "transactions",
      values: {
        date: "2026-05-06",
        merchant: [record("merchants.transit")],
        account: [record("accounts.card")],
        category: [record("categories.transport")],
        type: ["expense"],
        amount: "58.00",
        cleared: true,
      },
    },
    {
      key: "transactions.cafe_may_1",
      table: "transactions",
      values: {
        date: "2026-05-08",
        merchant: [record("merchants.cafe")],
        account: [record("accounts.card")],
        category: [record("categories.food")],
        type: ["expense"],
        amount: "12.60",
        cleared: true,
      },
    },
    {
      key: "transactions.bookshop_may",
      table: "transactions",
      values: {
        date: "2026-05-09",
        merchant: [record("merchants.bookshop")],
        account: [record("accounts.cash")],
        category: [record("categories.books")],
        type: ["expense"],
        amount: "31.90",
        cleared: true,
      },
    },
    {
      key: "transactions.market_may_2",
      table: "transactions",
      values: {
        date: "2026-05-11",
        merchant: [record("merchants.market")],
        account: [record("accounts.card")],
        category: [record("categories.groceries")],
        type: ["expense"],
        amount: "64.20",
        cleared: false,
      },
    },
    {
      key: "transactions.cafe_may_2",
      table: "transactions",
      values: {
        date: "2026-05-12",
        merchant: [record("merchants.cafe")],
        account: [record("accounts.card")],
        category: [record("categories.food")],
        type: ["expense"],
        amount: "9.90",
        cleared: false,
      },
    },
    { key: "budgets.rent", table: "budgets", values: { month: "2026-05-01", category: [record("categories.rent")], limit: "980.00" } },
    {
      key: "budgets.groceries",
      table: "budgets",
      values: { month: "2026-05-01", category: [record("categories.groceries")], limit: "450.00" },
    },
    {
      key: "budgets.transport",
      table: "budgets",
      values: { month: "2026-05-01", category: [record("categories.transport")], limit: "120.00" },
    },
    { key: "budgets.books", table: "budgets", values: { month: "2026-05-01", category: [record("categories.books")], limit: "80.00" } },
    { key: "budgets.food", table: "budgets", values: { month: "2026-05-01", category: [record("categories.food")], limit: "160.00" } },
  ],
  views: [
    {
      key: "recent_transactions",
      table: "transactions",
      name: "Recent transactions",
      shared: true,
      query: {
        sort: [{ fieldId: field("transactions.date"), direction: "desc" }],
        columns: [
          { fieldId: field("transactions.date") },
          { fieldId: field("transactions.merchant") },
          { fieldId: field("transactions.merchant_website"), label: "Merchant QR", format: { kind: "barcode", bcid: "qrcode" } },
          { fieldId: field("transactions.category") },
          { fieldId: field("transactions.type") },
          { fieldId: field("transactions.amount") },
          { fieldId: field("transactions.cleared") },
        ],
        limit: 50,
      },
    },
    {
      key: "transaction_calendar",
      table: "transactions",
      name: "Transaction calendar",
      shared: true,
      query: {
        sort: [{ fieldId: field("transactions.date"), direction: "desc" }],
        columns: [
          { fieldId: field("transactions.date") },
          { fieldId: field("transactions.merchant") },
          { fieldId: field("transactions.category") },
          { fieldId: field("transactions.type") },
          { fieldId: field("transactions.amount") },
        ],
        limit: 100,
      },
      displayConfig: {
        mode: "calendar",
        calendar: { dateFieldId: field("transactions.date") },
      },
    },
    {
      key: "monthly_income",
      table: "transactions",
      name: "Monthly income",
      shared: true,
      query: {
        filter: { op: "is", fieldId: field("transactions.type"), value: "income" },
        groupBy: [{ fieldId: field("transactions.date"), granularity: "month" }],
        aggregations: [{ fieldId: field("transactions.amount"), agg: "sum", label: "income" }],
      },
    },
    {
      key: "monthly_spend",
      table: "transactions",
      name: "Monthly spend",
      shared: true,
      query: {
        filter: { op: "is", fieldId: field("transactions.type"), value: "expense" },
        groupBy: [{ fieldId: field("transactions.date"), granularity: "month" }],
        aggregations: [{ fieldId: field("transactions.amount"), agg: "sum", label: "spent" }],
      },
    },
    {
      key: "spend_by_category",
      table: "transactions",
      name: "Spend by category",
      shared: true,
      query: {
        filter: { op: "is", fieldId: field("transactions.type"), value: "expense" },
        groupBy: [{ fieldId: field("transactions.category") }],
        aggregations: [{ fieldId: field("transactions.amount"), agg: "sum", label: "spent" }],
        groupSort: [{ fieldId: field("transactions.amount"), agg: "sum", direction: "desc" }],
      },
    },
    {
      key: "budgets",
      table: "budgets",
      name: "Monthly budgets",
      shared: true,
      query: {
        columns: [{ fieldId: field("budgets.month") }, { fieldId: field("budgets.category") }, { fieldId: field("budgets.limit") }],
        sort: [{ fieldId: field("budgets.limit"), direction: "desc" }],
      },
    },
  ],
  forms: [
    {
      key: "log_expense",
      table: "transactions",
      name: "Log expense",
      config: {
        title: "Log expense",
        description: "Add a purchase as an expense transaction.",
        submitLabel: "Log purchase",
        successMessage: "Expense logged.",
        fields: [
          { kind: "user_input", fieldId: field("transactions.date"), label: "Date", helpText: "Purchase date.", required: true },
          {
            kind: "user_input",
            fieldId: field("transactions.merchant"),
            label: "Merchant",
            helpText: "Where the purchase happened.",
            required: true,
            inlineCreate: {
              enabled: true,
              fields: [
                { fieldId: field("merchants.name"), label: "Merchant name", helpText: "Shop, vendor, or person.", required: true },
                { fieldId: field("merchants.website"), label: "Website", helpText: "Optional merchant URL." },
              ],
            },
          },
          {
            kind: "user_input",
            fieldId: field("transactions.account"),
            label: "Account",
            helpText: "Account or payment source.",
            required: true,
          },
          {
            kind: "user_input",
            fieldId: field("transactions.category"),
            label: "Category",
            helpText: "Budget or spending category.",
            required: true,
          },
          { kind: "user_input", fieldId: field("transactions.amount"), label: "Amount", helpText: "Expense amount.", required: true },
          { kind: "user_input", fieldId: field("transactions.notes"), label: "Notes", helpText: "Receipt details or context." },
          { kind: "form_value", fieldId: field("transactions.type"), value: ["expense"] },
          { kind: "form_value", fieldId: field("transactions.cleared"), value: true },
        ],
      },
    },
  ],
  dashboards: [
    {
      key: "overview",
      name: "Finance overview",
      description: "Current spending, recent purchases, budgets, and quick logging.",
      shared: true,
      config: {
        rows: [
          {
            id: "r_stats",
            kind: "row",
            height: "sm",
            cells: [
              {
                id: "w_income",
                kind: "stat",
                title: "Income",
                sub: "all recorded",
                icon: "ti ti-arrow-up-right",
                format: "currency",
                source: {
                  tableId: table("transactions"),
                  filter: { op: "is", fieldId: field("transactions.type"), value: "income" },
                  aggregations: [{ fieldId: field("transactions.amount"), agg: "sum" }],
                },
              },
              {
                id: "w_spend",
                kind: "stat",
                title: "Spend",
                sub: "all recorded",
                icon: "ti ti-arrow-down-right",
                format: "currency",
                source: {
                  tableId: table("transactions"),
                  filter: { op: "is", fieldId: field("transactions.type"), value: "expense" },
                  aggregations: [{ fieldId: field("transactions.amount"), agg: "sum" }],
                },
              },
              {
                id: "w_tx",
                kind: "stat",
                title: "Transactions",
                icon: "ti ti-receipt",
                format: "integer",
                source: { tableId: table("transactions"), aggregations: [{ fieldId: "*", agg: "count" }] },
              },
              {
                id: "w_budget",
                kind: "stat",
                title: "Budget",
                sub: "this month",
                icon: "ti ti-chart-pie",
                format: "currency",
                source: { tableId: table("budgets"), aggregations: [{ fieldId: field("budgets.limit"), agg: "sum" }] },
              },
            ],
          },
          {
            id: "r_charts",
            kind: "row",
            height: "md",
            cells: [
              {
                id: "w_spend_cat",
                kind: "chart",
                title: "Spend by category",
                subtitle: "Expense transactions only",
                chartType: "donut",
                viewId: view("spend_by_category"),
              },
              {
                id: "w_monthly",
                kind: "chart",
                title: "Monthly spend",
                chartType: "bar",
                viewId: view("monthly_spend"),
                format: "currency",
                yAxisLabel: "EUR",
              },
            ],
          },
          {
            id: "r_work",
            kind: "row",
            height: "lg",
            cells: [
              { id: "w_recent", kind: "view", title: "Recent transactions", source: { kind: "view", viewId: view("recent_transactions") } },
              { id: "w_log", kind: "form", title: "Log a purchase", formId: form("log_expense") },
            ],
          },
          {
            id: "r_budget",
            kind: "row",
            height: "md",
            cells: [
              { id: "w_budgets", kind: "view", title: "Monthly budgets", source: { kind: "view", viewId: view("budgets") } },
              {
                id: "w_income_chart",
                kind: "chart",
                title: "Monthly income",
                chartType: "bar",
                viewId: view("monthly_income"),
                format: "currency",
              },
            ],
          },
        ],
      },
    },
  ],
  defaultDashboard: "overview",
};
