import { createMockCover } from "@valentinkolb/cloud/shared";
import { currentMonthDate, field, form, formula, type GridTemplate, record, table, view } from "./types";

export const inventoryTemplate: GridTemplate = {
  id: "inventory",
  name: "Inventory",
  description: "Items, categories, locations, kits, and simple kit loans.",
  icon: "ti ti-packages",
  baseName: "Inventory",
  baseDescription: "Manage inventory, locations, kits, and loan requests.",
  tables: [
    {
      key: "categories",
      name: "Categories",
      fields: [
        {
          key: "name",
          name: "Name",
          description: "Category name shown on items and kits.",
          type: "text",
          required: true,
          presentable: true,
          icon: "ti ti-tag",
        },
        {
          key: "description",
          name: "Description",
          description: "Optional notes that explain what belongs in this category.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-align-left",
        },
      ],
    },
    {
      key: "locations",
      name: "Locations",
      fields: [
        {
          key: "name",
          name: "Name",
          description: "Location name shown in item records.",
          type: "text",
          required: true,
          presentable: true,
          icon: "ti ti-map-pin",
        },
        { key: "room", name: "Room", description: "Room or area where this location sits.", type: "text", icon: "ti ti-door" },
        { key: "shelf", name: "Shelf", description: "Shelf, cabinet, or bin identifier.", type: "text", icon: "ti ti-stack" },
        {
          key: "notes",
          name: "Notes",
          description: "Internal notes about this storage location.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-notes",
        },
      ],
    },
    {
      key: "items",
      name: "Items",
      displayConfig: {
        mode: "cards",
        cards: {
          imageFieldId: field("items.files"),
          fieldIds: [
            field("items.asset_id"),
            field("items.asset_barcode"),
            field("items.name"),
            field("items.category"),
            field("items.location"),
            field("items.status"),
            field("items.condition"),
            field("items.quantity"),
          ],
        },
      },
      fields: [
        {
          key: "asset_id",
          name: "Asset ID",
          description: "Server-generated inventory number for this item.",
          type: "id",
          config: { strategy: "sequence", prefix: "ITEM-", padding: 4 },
          presentable: true,
          icon: "ti ti-id",
        },
        {
          key: "asset_barcode",
          name: "Asset barcode",
          description: "Scannable barcode for the asset ID.",
          type: "formula",
          config: {
            expression: formula(field("items.asset_id")),
            format: { kind: "barcode", bcid: "code128", showText: true },
          },
          icon: "ti ti-barcode",
        },
        {
          key: "name",
          name: "Name",
          description: "Item name shown in inventory lists and cards.",
          type: "text",
          required: true,
          presentable: true,
          icon: "ti ti-package",
        },
        {
          key: "category",
          name: "Category",
          description: "Category this item belongs to.",
          type: "relation",
          icon: "ti ti-tag",
          config: { targetTableId: table("categories"), cardinality: "single" },
        },
        {
          key: "location",
          name: "Location",
          description: "Current storage location for this item.",
          type: "relation",
          icon: "ti ti-map-pin",
          config: { targetTableId: table("locations"), cardinality: "single" },
        },
        {
          key: "status",
          name: "Status",
          description: "Availability state used for filtering and loan planning.",
          type: "select",
          icon: "ti ti-traffic-lights",
          config: {
            options: [
              { id: "available", label: "Available", color: "#22c55e" },
              { id: "in_use", label: "In use", color: "#f59e0b" },
              { id: "maintenance", label: "Maintenance", color: "#ef4444" },
            ],
          },
          defaultValue: ["available"],
        },
        {
          key: "condition",
          name: "Condition",
          description: "Physical condition of this item.",
          type: "select",
          icon: "ti ti-stars",
          config: {
            options: [
              { id: "new", label: "New", color: "#22c55e" },
              { id: "good", label: "Good", color: "#3b82f6" },
              { id: "used", label: "Used", color: "#f59e0b" },
              { id: "repair", label: "Needs repair", color: "#ef4444" },
            ],
          },
        },
        {
          key: "serial_no",
          name: "Serial number",
          description: "Manufacturer serial number or other external identifier.",
          type: "text",
          icon: "ti ti-barcode",
        },
        {
          key: "tags",
          name: "Tags",
          description: "Reusable tags for item handling and search.",
          type: "select",
          icon: "ti ti-tags",
          config: {
            multiple: true,
            options: [
              { id: "portable", label: "Portable", color: "#3b82f6" },
              { id: "fragile", label: "Fragile", color: "#f59e0b" },
              { id: "calibrated", label: "Calibrated", color: "#22c55e" },
              { id: "shared", label: "Shared", color: "#8b5cf6" },
            ],
          },
        },
        {
          key: "quantity",
          name: "Quantity",
          description: "Number of units represented by this record.",
          type: "number",
          required: true,
          defaultValue: "1",
          config: { min: "0", decimalPlaces: 0 },
          icon: "ti ti-hash",
        },
        {
          key: "replacement_value",
          name: "Replacement value",
          description: "Estimated cost to replace one unit.",
          type: "number",
          config: {
            precision: 16,
            decimalPlaces: 2,
            unit: "EUR",
            unitPosition: "suffix",
          },
          icon: "ti ti-currency-euro",
        },
        {
          key: "total_value",
          name: "Total value",
          description: "Quantity multiplied by replacement value.",
          type: "formula",
          config: {
            expression: formula(field("items.quantity"), " * ", field("items.replacement_value")),
            format: {
              kind: "decimal",
              precision: 2,
              thousandsSeparator: true,
            },
          },
          icon: "ti ti-calculator",
        },
        {
          key: "purchase_date",
          name: "Purchase date",
          description: "Date this item was purchased or added.",
          type: "date",
          icon: "ti ti-calendar",
        },
        {
          key: "files",
          name: "Files",
          description: "Photos, manuals, receipts, or other attachments.",
          type: "file",
          icon: "ti ti-paperclip",
          config: { maxFiles: 5 },
        },
        {
          key: "notes",
          name: "Notes",
          description: "Internal notes about this item.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-notes",
        },
      ],
    },
    {
      key: "kits",
      name: "Kits",
      fields: [
        {
          key: "kit_code",
          name: "Kit code",
          description: "Short generated code for this kit.",
          type: "id",
          config: { strategy: "short_code", prefix: "KIT-", length: 6 },
          presentable: true,
          icon: "ti ti-id",
        },
        {
          key: "name",
          name: "Name",
          description: "Kit name shown to staff and requesters.",
          type: "text",
          required: true,
          presentable: true,
          icon: "ti ti-briefcase",
        },
        {
          key: "category",
          name: "Category",
          description: "Category this kit belongs to.",
          type: "relation",
          icon: "ti ti-tag",
          config: { targetTableId: table("categories"), cardinality: "single" },
        },
        {
          key: "items",
          name: "Items",
          description: "Inventory items included in this kit.",
          type: "relation",
          icon: "ti ti-packages",
          config: { targetTableId: table("items"), cardinality: "multiple" },
        },
        {
          key: "status",
          name: "Status",
          description: "Operational state of this kit.",
          type: "select",
          icon: "ti ti-circle-check",
          config: {
            options: [
              { id: "available", label: "Available", color: "#22c55e" },
              { id: "incomplete", label: "Incomplete", color: "#f59e0b" },
              { id: "internal", label: "Internal only", color: "#3b82f6" },
              { id: "retired", label: "Retired", color: "#94a3b8" },
            ],
          },
          defaultValue: ["available"],
        },
        {
          key: "requestable",
          name: "Requestable",
          description: "Whether this kit can be requested through forms.",
          type: "boolean",
          defaultValue: true,
          icon: "ti ti-world-check",
        },
        {
          key: "description",
          name: "Description",
          description: "Public-facing explanation of what the kit contains.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-align-left",
        },
        {
          key: "notes",
          name: "Admin notes",
          description: "Internal staff notes about this kit.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-notes",
        },
      ],
    },
    {
      key: "loans",
      name: "Loans",
      fields: [
        {
          key: "loan_no",
          name: "Loan number",
          description: "Generated loan request number.",
          type: "id",
          config: { strategy: "date_sequence", prefix: "LOAN-", period: "year", padding: 4 },
          presentable: true,
          icon: "ti ti-id",
        },
        {
          key: "requester_name",
          name: "Requester name",
          description: "Person requesting or borrowing the kit.",
          type: "text",
          required: true,
          presentable: true,
          icon: "ti ti-user",
        },
        {
          key: "requester_email",
          name: "Requester email",
          description: "Email address for loan communication.",
          type: "text",
          config: { regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" },
          icon: "ti ti-mail",
        },
        {
          key: "organization",
          name: "Organization",
          description: "Optional team, department, or external organization.",
          type: "text",
          icon: "ti ti-building",
        },
        {
          key: "kits",
          name: "Kits",
          description: "Kits requested or borrowed in this loan.",
          type: "relation",
          icon: "ti ti-briefcase",
          config: { targetTableId: table("kits"), cardinality: "multiple" },
        },
        {
          key: "start_date",
          name: "Requested from",
          description: "Requested start date for the loan.",
          type: "date",
          icon: "ti ti-calendar-plus",
        },
        {
          key: "due_date",
          name: "Due date",
          description: "Expected return date for borrowed kits.",
          type: "date",
          icon: "ti ti-calendar-due",
        },
        {
          key: "returned_at",
          name: "Returned at",
          description: "Actual date when the kits were returned.",
          type: "date",
          icon: "ti ti-calendar-check",
        },
        {
          key: "status",
          name: "Status",
          description: "Current approval and return status.",
          type: "select",
          icon: "ti ti-progress",
          config: {
            options: [
              { id: "requested", label: "Requested", color: "#3b82f6" },
              { id: "approved", label: "Approved", color: "#22c55e" },
              { id: "active", label: "Active", color: "#f59e0b" },
              { id: "returned", label: "Returned", color: "#94a3b8" },
              { id: "rejected", label: "Rejected", color: "#ef4444" },
            ],
          },
          defaultValue: ["requested"],
        },
        {
          key: "purpose",
          name: "Purpose",
          description: "Requester-provided reason for the loan.",
          type: "longtext",
          icon: "ti ti-message",
        },
        {
          key: "notes",
          name: "Admin notes",
          description: "Internal staff notes about this loan.",
          type: "longtext",
          config: { markdown: true },
          icon: "ti ti-notes",
        },
      ],
    },
  ],
  records: [
    {
      key: "categories.cameras",
      table: "categories",
      values: { name: "Cameras" },
    },
    { key: "categories.audio", table: "categories", values: { name: "Audio" } },
    {
      key: "categories.cables",
      table: "categories",
      values: { name: "Cables" },
    },
    {
      key: "locations.studio",
      table: "locations",
      values: { name: "Studio shelf", room: "Studio", shelf: "A2" },
    },
    {
      key: "locations.storage",
      table: "locations",
      values: { name: "Storage cabinet", room: "Storage", shelf: "C1" },
    },
    {
      key: "items.camera",
      table: "items",
      values: {
        name: "Sony A7 body",
        category: [record("categories.cameras")],
        location: [record("locations.studio")],
        status: ["available"],
        condition: ["good"],
        serial_no: "A7-001",
        tags: ["fragile", "portable"],
        quantity: "1",
        replacement_value: "1800.00",
        purchase_date: "2025-09-12",
      },
      files: [
        {
          field: "files",
          filename: "sony-a7-body.svg",
          dataUrl: createMockCover({ icon: "camera", theme: "blue", seed: "inventory:sony-a7-body", label: "Sony A7 body" }).dataUrl,
        },
      ],
    },
    {
      key: "items.mic",
      table: "items",
      values: {
        name: "Wireless mic set",
        category: [record("categories.audio")],
        location: [record("locations.studio")],
        status: ["available"],
        condition: ["good"],
        tags: ["portable", "shared"],
        quantity: "2",
        replacement_value: "320.00",
      },
      files: [
        {
          field: "files",
          filename: "wireless-mic-set.svg",
          dataUrl: createMockCover({ icon: "microphone", theme: "violet", seed: "inventory:wireless-mic-set", label: "Wireless mic set" })
            .dataUrl,
        },
      ],
    },
    {
      key: "items.hdmi",
      table: "items",
      values: {
        name: "HDMI cable 5m",
        category: [record("categories.cables")],
        location: [record("locations.storage")],
        status: ["available"],
        condition: ["used"],
        tags: ["shared"],
        quantity: "8",
        replacement_value: "18.00",
      },
      files: [
        {
          field: "files",
          filename: "hdmi-cable-5m.svg",
          dataUrl: createMockCover({ icon: "package", theme: "slate", seed: "inventory:hdmi-cable-5m", label: "HDMI cable 5m" }).dataUrl,
        },
      ],
    },
    {
      key: "kits.video",
      table: "kits",
      values: {
        name: "Video interview kit",
        category: [record("categories.cameras")],
        items: [record("items.camera"), record("items.mic"), record("items.hdmi")],
        status: ["available"],
        requestable: true,
        description: "Camera body, wireless mic set, and HDMI cable for interviews.",
      },
    },
    {
      key: "loans.demo",
      table: "loans",
      values: {
        requester_name: "Mara Example",
        requester_email: "mara@example.com",
        organization: "Design team",
        kits: [record("kits.video")],
        start_date: currentMonthDate(10),
        due_date: currentMonthDate(12),
        status: ["requested"],
        purpose: "Record a short product interview.",
      },
    },
    {
      key: "loans.demo_2",
      table: "loans",
      values: {
        requester_name: "Jonas Example",
        requester_email: "jonas@example.com",
        organization: "Training team",
        kits: [record("kits.video")],
        start_date: currentMonthDate(18),
        due_date: currentMonthDate(20),
        status: ["approved"],
        purpose: "Prepare a team training recording.",
      },
    },
  ],
  views: [
    {
      key: "available_items",
      table: "items",
      name: "Available items",
      shared: true,
      source: formula(
        "from table ",
        table("items"),
        "\nselect ",
        field("items.asset_barcode"),
        ", ",
        field("items.name"),
        ", ",
        field("items.category"),
        ", ",
        field("items.location"),
        ", ",
        field("items.quantity"),
        ", ",
        field("items.total_value"),
        "\nwhere ",
        field("items.status"),
        " = 'available'",
      ),
      ui: {
        columns: [
          { fieldId: field("items.asset_barcode"), label: "Asset ID", format: { kind: "barcode", bcid: "code128", showText: true } },
          { fieldId: field("items.name") },
          { fieldId: field("items.category") },
          { fieldId: field("items.location") },
          { fieldId: field("items.quantity") },
          { fieldId: field("items.total_value") },
        ],
        displayConfig: {
          mode: "cards",
          cards: {
            imageFieldId: field("items.files"),
            fieldIds: [
              field("items.asset_id"),
              field("items.asset_barcode"),
              field("items.name"),
              field("items.category"),
              field("items.location"),
              field("items.status"),
              field("items.quantity"),
            ],
          },
        },
      },
    },
    {
      key: "stock_by_category",
      table: "items",
      name: "Stock by category",
      shared: true,
      source: formula(
        "from table ",
        table("items"),
        "\ngroup by ",
        field("items.category"),
        "\naggregate sum(",
        field("items.quantity"),
        ") as units, count(*) as items\nsort units desc",
      ),
    },
    {
      key: "open_loans",
      table: "loans",
      name: "Open loans",
      shared: true,
      source: formula(
        "from table ",
        table("loans"),
        "\nselect ",
        field("loans.requester_name"),
        ", ",
        field("loans.organization"),
        ", ",
        field("loans.kits"),
        ", ",
        field("loans.start_date"),
        ", ",
        field("loans.due_date"),
        ", ",
        field("loans.status"),
        "\nwhere oneof(",
        field("loans.status"),
        ", 'requested', 'approved', 'active')\nsort ",
        field("loans.due_date"),
        " asc",
      ),
      ui: {
        displayConfig: {
          mode: "calendar",
          calendar: { dateFieldId: field("loans.due_date") },
        },
      },
    },
    {
      key: "items_count",
      table: "items",
      name: "Items count",
      shared: true,
      source: formula("from table ", table("items"), "\naggregate count(*) as items"),
    },
    {
      key: "kits_count",
      table: "kits",
      name: "Kits count",
      shared: true,
      source: formula("from table ", table("kits"), "\naggregate count(*) as kits"),
    },
    {
      key: "open_loans_count",
      table: "loans",
      name: "Open loans count",
      shared: true,
      source: formula(
        "from table ",
        table("loans"),
        "\nwhere oneof(",
        field("loans.status"),
        ", 'requested', 'approved', 'active')\naggregate count(*) as open_loans",
      ),
    },
  ],
  forms: [
    {
      key: "add_item",
      table: "items",
      name: "Add item",
      config: {
        title: "Add item",
        submitLabel: "Add item",
        successMessage: "Item added.",
        fields: [
          {
            kind: "user_input",
            fieldId: field("items.name"),
            label: "Item name",
            helpText: "Name shown in inventory lists.",
            required: true,
          },
          {
            kind: "user_input",
            fieldId: field("items.category"),
            label: "Category",
            helpText: "Pick an existing category or create one inline.",
            inlineCreate: {
              enabled: true,
              fields: [
                {
                  fieldId: field("categories.name"),
                  label: "Category name",
                  helpText: "Short category name, for example Cameras.",
                  required: true,
                },
              ],
            },
          },
          {
            kind: "user_input",
            fieldId: field("items.location"),
            label: "Location",
            helpText: "Where this item is stored.",
            inlineCreate: {
              enabled: true,
              fields: [
                {
                  fieldId: field("locations.name"),
                  label: "Location name",
                  helpText: "Readable location label.",
                  required: true,
                },
                {
                  fieldId: field("locations.room"),
                  label: "Room",
                  helpText: "Room or area.",
                },
                {
                  fieldId: field("locations.shelf"),
                  label: "Shelf",
                  helpText: "Shelf, box, or cabinet.",
                },
              ],
            },
          },
          {
            kind: "user_input",
            fieldId: field("items.status"),
            label: "Status",
            helpText: "Current availability.",
            defaultValue: ["available"],
          },
          {
            kind: "user_input",
            fieldId: field("items.condition"),
            label: "Condition",
            helpText: "Physical state of the item.",
          },
          {
            kind: "user_input",
            fieldId: field("items.tags"),
            label: "Tags",
            helpText: "Optional handling or usage labels.",
          },
          {
            kind: "user_input",
            fieldId: field("items.quantity"),
            label: "Quantity",
            helpText: "How many units are available.",
            required: true,
            defaultValue: "1",
          },
          {
            kind: "user_input",
            fieldId: field("items.replacement_value"),
            label: "Replacement value",
            helpText: "Cost to replace one unit.",
          },
          {
            kind: "user_input",
            fieldId: field("items.notes"),
            label: "Notes",
            helpText: "Extra context for admins.",
          },
        ],
      },
    },
    {
      key: "request_loan",
      table: "loans",
      name: "Request loan",
      isPublic: true,
      config: {
        title: "Request kit loan",
        description: "Choose one or more kits. An admin reviews and approves the request.",
        submitLabel: "Request loan",
        successMessage: "Loan requested.",
        fields: [
          {
            kind: "user_input",
            fieldId: field("loans.requester_name"),
            label: "Name",
            helpText: "Who should receive the kit.",
            required: true,
          },
          {
            kind: "user_input",
            fieldId: field("loans.requester_email"),
            label: "Email",
            helpText: "Contact address for questions and approval.",
            required: true,
          },
          {
            kind: "user_input",
            fieldId: field("loans.organization"),
            label: "Organization",
            helpText: "Team, company, or project.",
          },
          {
            kind: "user_input",
            fieldId: field("loans.kits"),
            label: "Kits",
            helpText: "Choose one or more kits to borrow.",
            required: true,
          },
          {
            kind: "user_input",
            fieldId: field("loans.start_date"),
            label: "Start date",
            helpText: "First planned day of use.",
          },
          {
            kind: "user_input",
            fieldId: field("loans.due_date"),
            label: "Due date",
            helpText: "Planned return date.",
          },
          {
            kind: "user_input",
            fieldId: field("loans.purpose"),
            label: "Purpose",
            helpText: "What the kit will be used for.",
          },
          {
            kind: "form_value",
            fieldId: field("loans.status"),
            value: ["requested"],
          },
        ],
      },
    },
  ],
  dashboards: [
    {
      key: "overview",
      name: "Inventory overview",
      description: "Inventory value, open loan requests, and quick entry.",
      shared: true,
      config: {
        rows: [
          {
            id: "r_stats",
            kind: "row",
            height: "sm",
            cells: [
              {
                id: "w_items",
                kind: "stat",
                title: "Items",
                icon: "ti ti-packages",
                format: "integer",
                viewId: view("items_count"),
              },
              {
                id: "w_kits",
                kind: "stat",
                title: "Kits",
                icon: "ti ti-briefcase",
                format: "integer",
                viewId: view("kits_count"),
              },
              {
                id: "w_open_loans",
                kind: "stat",
                title: "Open loans",
                icon: "ti ti-calendar-due",
                format: "integer",
                viewId: view("open_loans_count"),
              },
            ],
          },
          {
            id: "r_main",
            kind: "row",
            height: "md",
            cells: [
              {
                id: "w_available",
                kind: "view",
                title: "Available items",
                viewId: view("available_items"),
              },
              {
                id: "w_add",
                kind: "form",
                title: "Add item",
                formId: form("add_item"),
              },
              {
                id: "w_stock_by_category",
                kind: "chart",
                title: "Stock by category",
                subtitle: "Available units per category",
                chartType: "bar",
                viewId: view("stock_by_category"),
              },
            ],
          },
          {
            id: "r_bottom",
            kind: "row",
            height: "md",
            cells: [
              {
                id: "w_open",
                kind: "view",
                title: "Open loans",
                viewId: view("open_loans"),
                span: 6,
              },
              {
                id: "w_rules",
                kind: "markdown",
                title: "Loan rules",
                markdown:
                  "### Loan rules\n\n- Requests start as **requested**.\n- Admins approve requests before pickup.\n- Mark a loan as returned when all kits are back.",
                span: 6,
              },
            ],
          },
        ],
      },
    },
  ],
  documentTemplates: [
    {
      key: "loan_agreement",
      table: "loans",
      starterId: "loan-agreement",
      name: "Loan agreement",
      description: "Printable loan agreement for one inventory loan.",
      source: formula(
        "from table ",
        table("loans"),
        "\nselect ",
        field("loans.loan_no"),
        " as loan_number",
        ", ",
        field("loans.requester_name"),
        " as borrower_name",
        ", ",
        field("loans.requester_email"),
        " as borrower_email",
        ", ",
        field("loans.organization"),
        " as borrower_organization",
        ", ",
        field("loans.kits"),
        ", ",
        field("loans.start_date"),
        " as loan_start",
        ", ",
        field("loans.due_date"),
        " as return_due",
        ", ",
        field("loans.purpose"),
        "\nwhere record.id = '{{ record.id }}'\nlimit 1",
      ),
      enabled: true,
    },
  ],
  emailTemplates: [
    {
      key: "loan_agreement_ready",
      name: "Loan agreement ready",
      description: "Sends a private download link for a generated loan agreement.",
      subject: "Loan agreement {{ data.loanNumber | default: 'ready' }}",
      html: `<main style="font-family:Arial,sans-serif;color:#111827;line-height:1.5;max-width:640px;margin:0 auto;padding:32px;">
  <h1 style="font-size:24px;margin:0 0 16px;">Your loan agreement is ready</h1>
  <p>Hello {{ data.requesterName | default: "there" }},</p>
  <p>Your agreement{% if data.loanNumber %} for loan <strong>{{ data.loanNumber }}</strong>{% endif %} has been prepared.{% if data.dueDate %} The planned return date is <strong>{{ data.dueDate }}</strong>.{% endif %}</p>
  <p style="margin:24px 0;"><a href="{{ data.agreement.url }}" style="display:inline-block;background:#2563eb;color:#fff;text-decoration:none;padding:12px 18px;border-radius:6px;">Download agreement</a></p>
  <p style="color:#6b7280;font-size:14px;">This private link expires automatically.</p>
</main>`,
      enabled: true,
    },
  ],
  workflows: [
    {
      key: "send_loan_agreement",
      name: "Send loan agreement",
      description: "Generates a loan agreement, creates a private download link, and emails it to the requester.",
      source: `inputs:
  loan:
    type: record
    table: Loans
    label: Loan
    required: true
steps:
  - generateDocument:
      template: Loan agreement
      record: inputs.loan
      saveAs: agreementPdf
  - createDocumentLink:
      document: agreementPdf
      expiresIn: 30d
      saveAs: agreementLink
  - sendEmail:
      template: Loan agreement ready
      to:
        - email: \${{ inputs.loan.Requester email }}
      data:
        agreement: \${{ agreementLink }}
        loanNumber: \${{ inputs.loan.Loan number }}
        requesterName: \${{ inputs.loan.Requester name }}
        dueDate: \${{ inputs.loan.Due date }}
  - succeed:
      message: Loan agreement sent.`,
      enabled: true,
    },
  ],
  defaultDashboard: "overview",
};
