/**
 * Core platform API surface — owned by cloud-lib, mounted by the core-app.
 *
 * Lives here (not in an app) because every container shares the same auth
 * model, self-service shape, lifecycle controls and entity search; redefining
 * any of these per-app would break the platform invariant.
 *
 * Apps that need a typed client to these routes import from
 * `@valentinkolb/cloud/clients/core`. The client and the routes share their
 * type via `CoreApiType` below.
 *
 * The OpenAPI spec for these routes is generated by `defineApp` (driven by
 * core's `openapi: "/api/openapi.json"` opt-in) — this file no longer mounts
 * any docs UI; the api-docs aggregator at `/app/api-docs` is the only consumer.
 */
import { Hono } from "hono";
import { prettyJSON } from "hono/pretty-json";
import accountsEntitiesRoutes from "./accounts-entities";
import adminCoreSettingsRoutes from "./admin-core-settings";
import adminLifecycleRoutes from "./admin-lifecycle";
import { adminAnnouncementRoutes, announcementRoutes } from "./announcements";
import authRoutes from "./auth";
import meRoutes from "./me";
import { createSearchRoutes } from "./search";

/**
 * Single-expression chain so `typeof buildCoreApi()` captures every route's
 * input/output. Splitting into `new Hono()` + `.route(...)` calls would erase
 * the typed shape for the client.
 */
const buildCoreApi = () => {
  const searchRoutes = createSearchRoutes();
  return new Hono()
    .use(prettyJSON())
    .route("/auth", authRoutes)
    .route("/me", meRoutes)
    .route("/accounts", accountsEntitiesRoutes)
    .route("/announcements", announcementRoutes)
    .route("/admin/core/announcements", adminAnnouncementRoutes)
    .route("/admin/core/settings", adminCoreSettingsRoutes)
    .route("/admin/lifecycle", adminLifecycleRoutes)
    .route("/", searchRoutes);
};

/** Type of the entire core HTTP surface — consumed by the client builder. */
export type CoreApiType = ReturnType<typeof buildCoreApi>;

/**
 * Build the core router. The core-app calls this and mounts the returned
 * router under `/api`.
 */
export const createCoreApiRouter = () => {
  const api = buildCoreApi();
  api.all("/*", (c) => c.json({ message: "API route not found" }, 404));
  return { api };
};
