import { describe, expect, test } from "bun:test";
import type { DocumentRunSummary } from "../../../contracts";
import { mergeRefreshedWorkflowRunDocuments } from "./workflow-run-documents";

const document = (id: string): DocumentRunSummary => ({ id }) as DocumentRunSummary;

describe("mergeRefreshedWorkflowRunDocuments", () => {
  test("preserves loaded pages while prepending documents generated by an active run", () => {
    expect(
      mergeRefreshedWorkflowRunDocuments(
        {
          items: [document("old-1"), document("old-2"), document("old-3")],
          total: 4,
          hasMore: true,
          nextOffset: 3,
        },
        {
          items: [document("new"), document("old-1"), document("old-2")],
          total: 5,
          hasMore: true,
          nextOffset: 3,
        },
      ),
    ).toEqual({
      items: [document("new"), document("old-1"), document("old-2"), document("old-3")],
      total: 5,
      hasMore: true,
      nextOffset: 4,
    });
  });

  test("uses the refreshed first page when no additional page is loaded", () => {
    const refreshed = { items: [document("new")], total: 1, hasMore: false, nextOffset: null };
    expect(mergeRefreshedWorkflowRunDocuments({ items: [], total: 0, hasMore: false, nextOffset: null }, refreshed)).toBe(refreshed);
  });
});
