import { login, changeExpiredPassword, changePassword, getServiceSession } from "./auth";
import {
  get as userGet,
  getByUid,
  list as userList,
  getGroups,
  getManagedGroups,
  addGuest,
  addIpa,
  updateProfile,
  updateSshKeys,
  resetPassword,
  setExpiry as userSetExpiry,
  demoteToGuest,
  deleteUser,
} from "./users";
import {
  get as groupGet,
  list as groupList,
  getMembers,
  getManagers,
  getParents,
  getManagedGroups as groupGetManagedGroups,
  add as groupAdd,
  update as groupUpdate,
  del as groupDel,
  makePosix,
  addMember,
  removeMember,
  addManager,
  removeManager,
} from "./groups";
import {
  hostList,
  hostGet,
  hostMod,
  hostDel,
  hostAddToGroup,
  hostRemoveFromGroup,
  hostgroupList,
  hostgroupGet,
  hostgroupAdd,
  hostgroupMod,
  hostgroupDel,
  hostListByGroup,
} from "./hosts";
import { syncFromIpa, startSyncInterval, stopSyncInterval, syncUser } from "./sync";
import { search } from "./search";

export const ipa = {
  auth: { login, changeExpiredPassword, changePassword, getServiceSession },
  users: {
    get: userGet,
    getByUid,
    list: userList,
    getGroups,
    getManagedGroups,
    addGuest,
    addIpa,
    updateProfile,
    updateSshKeys,
    resetPassword,
    setExpiry: userSetExpiry,
    demoteToGuest,
    delete: deleteUser,
  },
  groups: {
    get: groupGet,
    list: groupList,
    getMembers,
    getManagers,
    getParents,
    getManagedGroups: groupGetManagedGroups,
    add: groupAdd,
    update: groupUpdate,
    delete: groupDel,
    makePosix,
    addMember,
    removeMember,
    addManager,
    removeManager,
  },
  hosts: {
    list: hostList,
    listByGroup: hostListByGroup,
    get: hostGet,
    mod: hostMod,
    del: hostDel,
    addToGroup: hostAddToGroup,
    removeFromGroup: hostRemoveFromGroup,
  },
  hostgroups: {
    list: hostgroupList,
    get: hostgroupGet,
    add: hostgroupAdd,
    mod: hostgroupMod,
    del: hostgroupDel,
  },
  search,
  sync: {
    start: startSyncInterval,
    stop: stopSyncInterval,
    run: syncFromIpa,
    user: syncUser,
  },
};
