import type {
  DslQueryCompletionItem,
  DslQueryCompletionKind,
  DslQueryTextRange,
  WorkflowDefinition,
  WorkflowInputType,
} from "../contracts";
import type { WorkflowCatalog, WorkflowCatalogEntry } from "../service/workflows";
import { validateWorkflowReferences } from "../service/workflows";
import { parseWorkflowYaml, type WorkflowDiagnostic } from "./dsl";

type InputRef = {
  name: string;
  type: WorkflowInputType;
  table?: string;
};

type BuildWorkflowIntelligenceParams = {
  source: string;
  caret: number;
  catalog: WorkflowCatalog;
};

const TOP_LEVEL_KEYS = [
  { label: "inputs", insertText: "inputs:\n  ", detail: "Declare typed workflow inputs" },
  { label: "triggers", insertText: "triggers:\n  ", detail: "Declare how this workflow starts" },
  { label: "steps", insertText: "steps:\n  - ", detail: "Declare actions and control flow" },
];

const TRIGGER_KEYS = [
  { label: "form", insertText: "form: {}", detail: "Run from an autogenerated form" },
  { label: "api", insertText: "api:\n  enabled: true", detail: "Run from an authenticated API request" },
  { label: "scanner", insertText: "scanner:\n  input: ", detail: "Resolve scanned text into a record input" },
  { label: "bulkSelection", insertText: "bulkSelection:\n  input: ", detail: "Run for a server-side record selection" },
  { label: "dashboardButton", insertText: "dashboardButton:\n  label: Run workflow", detail: "Expose as a dashboard button" },
  { label: "schedule", insertText: "schedule:\n  cron: '0 9 * * 1-5'", detail: "Run from a five-field cron schedule" },
  { label: "recordEvent", insertText: "recordEvent:\n  event: updated\n  input: ", detail: "Run when records change" },
];

const INPUT_KEYS = [
  { label: "type", insertText: "type: ", detail: "Input type" },
  { label: "table", insertText: "table: ", detail: "Required for record inputs" },
  { label: "required", insertText: "required: true", detail: "Require the user or trigger to provide this input" },
  { label: "options", insertText: "options:\n      - ", detail: "Allowed values for select inputs" },
];

const INPUT_TYPES: WorkflowInputType[] = ["text", "number", "boolean", "date", "dateTime", "select", "record", "recordList"];
const RECORD_EVENT_VALUES = ["created", "updated", "deleted"];
const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"];
const SCANNER_RESOLVE_MODES = ["scanCode", "field"];
const DOCUMENT_LINK_TTLS = ["1d", "7d", "30d", "90d"];
const FUNCTIONS = ["now()"];

const STEP_SNIPPETS = [
  {
    label: "updateRecord",
    insertText: "updateRecord:\n    record: inputs.\n    set:\n      ",
    detail: "Update fields on an existing record",
  },
  { label: "createRecord", insertText: "createRecord:\n    table: \n    values:\n      ", detail: "Create a record in a table" },
  { label: "generateDocument", insertText: "generateDocument:\n    template: \n    record: inputs.", detail: "Generate a PDF document" },
  {
    label: "createDocumentLink",
    insertText: "createDocumentLink:\n    document: \n    expiresIn: 30d\n    saveAs: documentLink",
    detail: "Create an expiring public document link",
  },
  {
    label: "sendEmail",
    insertText: "sendEmail:\n    template: \n    to:\n      - email: \n    data:\n      ",
    detail: "Send an email from a Grids email template",
  },
  {
    label: "httpRequest",
    insertText: "httpRequest:\n    method: POST\n    url: https://example.com\n    json:\n      ",
    detail: "Send a JSON HTTP request",
  },
  { label: "setVariable", insertText: "setVariable:\n    name: value\n    value: ", detail: "Store a value for later steps" },
  { label: "if", insertText: "if:\n    equals: [, ]\n  then:\n    - ", detail: "Branch when a condition matches" },
  { label: "switch", insertText: "switch: \n  cases:\n    - when: \n      do:\n        - ", detail: "Branch by value" },
  { label: "forEach", insertText: "forEach: inputs.\n  as: item\n  do:\n    - ", detail: "Loop over a recordList input" },
  { label: "fail", insertText: "fail:\n    message: ", detail: "Stop the workflow with an error" },
];

const uniqueEntries = <T extends WorkflowCatalogEntry>(entries: Iterable<T>): T[] => {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const entry of entries) {
    if (seen.has(entry.id)) continue;
    seen.add(entry.id);
    out.push(entry);
  }
  return out.sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
};

const catalogTables = (catalog: WorkflowCatalog): WorkflowCatalogEntry[] => uniqueEntries(catalog.tables.refs.values());

const catalogTemplates = (catalog: WorkflowCatalog): Array<WorkflowCatalogEntry & { tableId: string }> =>
  uniqueEntries(catalog.templates.refs.values());

const catalogEmailTemplates = (catalog: WorkflowCatalog): WorkflowCatalogEntry[] => uniqueEntries(catalog.emailTemplates.refs.values());

const catalogFields = (catalog: WorkflowCatalog): Array<WorkflowCatalogEntry & { tableId: string; tableName: string }> => {
  const tables = new Map(catalogTables(catalog).map((table) => [table.id, table.name]));
  const out: Array<WorkflowCatalogEntry & { tableId: string; tableName: string }> = [];
  for (const [tableId, fields] of catalog.fieldsByTable) {
    const tableName = tables.get(tableId) ?? "Table";
    for (const field of uniqueEntries(fields.refs.values())) out.push({ ...field, tableId, tableName });
  }
  return out.sort((a, b) => a.tableName.localeCompare(b.tableName) || a.name.localeCompare(b.name));
};

const completionItem = (
  range: DslQueryTextRange,
  kind: DslQueryCompletionKind,
  label: string,
  insertText: string,
  detail?: string,
): DslQueryCompletionItem => ({
  label,
  kind,
  insertText,
  textEdit: { ...range, text: insertText },
  ...(detail ? { detail } : {}),
});

const rankItems = (source: string, range: DslQueryTextRange, items: DslQueryCompletionItem[]): DslQueryCompletionItem[] => {
  const needle = source.slice(range.start, range.end).trim().toLowerCase();
  return items
    .filter((item) => !needle || `${item.label} ${item.detail ?? ""} ${item.insertText}`.toLowerCase().includes(needle))
    .sort((a, b) => {
      const aPrefix = a.label.toLowerCase().startsWith(needle) ? 0 : 1;
      const bPrefix = b.label.toLowerCase().startsWith(needle) ? 0 : 1;
      return aPrefix - bPrefix || a.label.localeCompare(b.label);
    })
    .slice(0, 80);
};

const lineInfoAt = (source: string, caret: number) => {
  const lineStart = source.lastIndexOf("\n", Math.max(0, caret - 1)) + 1;
  const lineEnd = source.indexOf("\n", caret);
  const absoluteLineEnd = lineEnd === -1 ? source.length : lineEnd;
  const before = source.slice(lineStart, caret);
  const full = source.slice(lineStart, absoluteLineEnd);
  const indent = before.match(/^\s*/)?.[0].length ?? 0;
  return { lineStart, before, full, indent };
};

const tokenRange = (source: string, caret: number): DslQueryTextRange => {
  let start = caret;
  while (start > 0 && !/[\s:[\]{},]/.test(source[start - 1]!)) start -= 1;
  return { start, end: caret };
};

const valueRange = (source: string, caret: number, lineStart: number, before: string): DslQueryTextRange => {
  const colon = before.indexOf(":");
  if (colon < 0) return tokenRange(source, caret);
  let start = lineStart + colon + 1;
  while (start < caret && /\s/.test(source[start]!)) start += 1;
  return { start, end: caret };
};

const yamlPathBeforeLine = (source: string, caret: number): string[] => {
  const { lineStart } = lineInfoAt(source, caret);
  const lines = source.slice(0, lineStart).split(/\n/);
  const stack: Array<{ indent: number; key: string }> = [];
  for (const line of lines) {
    const match = /^(\s*)(?:-\s*)?([A-Za-z][A-Za-z0-9]*):/.exec(line);
    if (!match) continue;
    const indent = match[1]!.length;
    while (stack.length > 0 && stack[stack.length - 1]!.indent >= indent) stack.pop();
    stack.push({ indent, key: match[2]! });
  }
  return stack.map((item) => item.key);
};

const parsedInputs = (definition: WorkflowDefinition | null): InputRef[] => {
  if (!definition?.inputs) return [];
  return Object.entries(definition.inputs).map(([name, input]) => ({
    name,
    type: input.type,
    ...(input.table ? { table: input.table } : {}),
  }));
};

const looseInputs = (source: string): InputRef[] => {
  const inputs: InputRef[] = [];
  let inInputs = false;
  let current: InputRef | null = null;
  for (const line of source.split(/\n/)) {
    const top = /^([A-Za-z][A-Za-z0-9]*):/.exec(line);
    if (top) {
      inInputs = top[1] === "inputs";
      current = null;
      continue;
    }
    if (!inInputs) continue;
    const input = /^  ([A-Za-z_][A-Za-z0-9_]*):\s*$/.exec(line);
    if (input) {
      current = { name: input[1]!, type: "text" };
      inputs.push(current);
      continue;
    }
    if (!current) continue;
    const type = /^    type:\s*([A-Za-z][A-Za-z0-9]*)/.exec(line);
    if (type && INPUT_TYPES.includes(type[1] as WorkflowInputType)) current.type = type[1] as WorkflowInputType;
    const table = /^    table:\s*(.+?)\s*$/.exec(line);
    if (table) current.table = table[1]!;
  }
  return inputs;
};

const inputItems = (range: DslQueryTextRange, inputs: InputRef[], type?: WorkflowInputType): DslQueryCompletionItem[] =>
  inputs
    .filter((input) => !type || input.type === type)
    .map((input) => completionItem(range, "literal", input.name, input.name, `${input.type}${input.table ? ` · ${input.table}` : ""}`));

const inputPathItems = (range: DslQueryTextRange, inputs: InputRef[], type?: WorkflowInputType): DslQueryCompletionItem[] =>
  inputs
    .filter((input) => !type || input.type === type)
    .map((input) =>
      completionItem(
        range,
        "literal",
        `inputs.${input.name}`,
        `inputs.${input.name}`,
        `${input.type}${input.table ? ` · ${input.table}` : ""}`,
      ),
    );

const keyItems = (
  source: string,
  range: DslQueryTextRange,
  keys: Array<{ label: string; insertText: string; detail: string }>,
): DslQueryCompletionItem[] =>
  rankItems(
    source,
    range,
    keys.map((item) => completionItem(range, "keyword", item.label, item.insertText, item.detail)),
  );

const listItems = (source: string, range: DslQueryTextRange, values: string[], detail: string): DslQueryCompletionItem[] =>
  rankItems(
    source,
    range,
    values.map((value) => completionItem(range, "literal", value, value, detail)),
  );

const valueItems = (params: {
  source: string;
  range: DslQueryTextRange;
  key: string;
  path: string[];
  inputs: InputRef[];
  catalog: WorkflowCatalog;
}): DslQueryCompletionItem[] => {
  const { source, range, key, path, inputs, catalog } = params;
  if (key === "type") return listItems(source, range, INPUT_TYPES, "Workflow input type");
  if (key === "event") return listItems(source, range, RECORD_EVENT_VALUES, "Record event");
  if (key === "method") return listItems(source, range, HTTP_METHODS, "HTTP method");
  if (key === "by") return listItems(source, range, SCANNER_RESOLVE_MODES, "Scanner resolve mode");
  if (key === "table") {
    return rankItems(
      source,
      range,
      catalogTables(catalog).map((table) => completionItem(range, "source", table.name, table.name, `table · ${table.shortId}`)),
    );
  }
  if (key === "template") {
    if (path.includes("sendEmail")) {
      return rankItems(
        source,
        range,
        catalogEmailTemplates(catalog).map((template) =>
          completionItem(range, "source", template.name, template.name, `email template · ${template.shortId}`),
        ),
      );
    }
    return rankItems(
      source,
      range,
      catalogTemplates(catalog).map((template) =>
        completionItem(range, "source", template.name, template.name, `document template · ${template.shortId}`),
      ),
    );
  }
  if (key === "field") {
    return rankItems(
      source,
      range,
      catalogFields(catalog).map((field) =>
        completionItem(range, "field", field.name, field.name, `${field.tableName} · ${field.shortId}`),
      ),
    );
  }
  if (key === "input") {
    const parent = path[path.length - 1];
    if (parent === "bulkSelection") return rankItems(source, range, inputItems(range, inputs, "recordList"));
    if (parent === "scanner" || parent === "recordEvent") return rankItems(source, range, inputItems(range, inputs, "record"));
    return rankItems(source, range, inputItems(range, inputs));
  }
  if (key === "record") return rankItems(source, range, inputPathItems(range, inputs, "record"));
  if (key === "forEach") return rankItems(source, range, inputPathItems(range, inputs, "recordList"));
  if (key === "expiresIn") return listItems(source, range, DOCUMENT_LINK_TTLS, "Document link lifetime");
  if (key === "value" || key === "url" || key === "filename")
    return rankItems(
      source,
      range,
      FUNCTIONS.map((fn) => completionItem(range, "function", fn, fn, "Workflow function")),
    );
  return [];
};

const isStepContext = (path: string[]): boolean => path.some((part) => ["steps", "then", "else", "do", "default"].includes(part));

export const buildWorkflowIntelligence = ({ source, caret, catalog }: BuildWorkflowIntelligenceParams): DslQueryCompletionItem[] => {
  const clampedCaret = Math.min(Math.max(caret, 0), source.length);
  const parsed = parseWorkflowYaml(source);
  const definition = parsed.ok ? parsed.definition : null;
  const inputs = definition ? parsedInputs(definition) : looseInputs(source);
  const line = lineInfoAt(source, clampedCaret);
  const path = yamlPathBeforeLine(source, clampedCaret);
  const keyMatch = /^\s*(?:-\s*)?([A-Za-z][A-Za-z0-9]*)\s*:\s*/.exec(line.before);
  if (keyMatch) {
    const range = valueRange(source, clampedCaret, line.lineStart, line.before);
    return valueItems({ source, range, key: keyMatch[1]!, path, inputs, catalog });
  }

  const range = tokenRange(source, clampedCaret);
  if (isStepContext(path) && /^\s*-\s*[A-Za-z0-9_]*$/.test(line.before)) {
    return rankItems(
      source,
      range,
      STEP_SNIPPETS.map((step) => completionItem(range, "keyword", step.label, step.insertText, step.detail)),
    );
  }
  const parent = path[path.length - 1];
  if (!parent) return keyItems(source, range, TOP_LEVEL_KEYS);
  if (parent === "triggers") return keyItems(source, range, TRIGGER_KEYS);
  if (path[path.length - 2] === "inputs") return keyItems(source, range, INPUT_KEYS);
  return [];
};

export const workflowDiagnostics = (source: string, catalog: WorkflowCatalog): WorkflowDiagnostic[] => {
  const parsed = parseWorkflowYaml(source);
  if (!parsed.ok) return parsed.diagnostics;
  return validateWorkflowReferences(parsed.definition, catalog).map((message) => ({ message }));
};
