export const PULSE_EXTERNAL_INGEST_COLLECTION_LIMIT = 500;
export const PULSE_EXTERNAL_INGEST_BATCH_LIMIT = 1_500;
export const PULSE_INTERNAL_INGEST_BATCH_LIMIT = 50_000;
export const PULSE_INGEST_IDEMPOTENCY_KEY_MAX_LENGTH = 200;
export const PULSE_INGEST_IDEMPOTENCY_TTL_HOURS = 24;
