import type { IconOption } from "./SpecialInputs";

const icon = (name: string, label: string, keywords: readonly string[] = []): IconOption => ({
  value: `ti ti-${name}`,
  label,
  icon: `ti ti-${name}`,
  keywords: [name, ...keywords],
});

/**
 * A compact, application-neutral Tabler catalogue for IconInput.
 * Consumers can still replace it with a domain-specific option list.
 */
export const DEFAULT_ICON_OPTIONS: readonly IconOption[] = [
  icon("activity", "Activity", ["pulse", "monitor"]),
  icon("adjustments", "Adjustments", ["settings", "controls"]),
  icon("alert-circle", "Alert", ["warning", "error"]),
  icon("archive", "Archive", ["box", "storage"]),
  icon("bell", "Bell", ["notification"]),
  icon("book", "Book", ["docs", "read"]),
  icon("bookmark", "Bookmark", ["save", "favorite"]),
  icon("box", "Box", ["package", "inventory"]),
  icon("briefcase", "Briefcase", ["work", "business"]),
  icon("building", "Building", ["company", "office"]),
  icon("calendar", "Calendar", ["date", "schedule"]),
  icon("camera", "Camera", ["photo", "image"]),
  icon("chart-bar", "Bar chart", ["analytics", "stats"]),
  icon("chart-line", "Line chart", ["analytics", "trend"]),
  icon("check", "Check", ["done", "success"]),
  icon("circle-check", "Check circle", ["done", "success"]),
  icon("clipboard", "Clipboard", ["copy", "paste"]),
  icon("clock", "Clock", ["time", "schedule"]),
  icon("cloud", "Cloud", ["hosting", "online"]),
  icon("code", "Code", ["source", "developer"]),
  icon("coin", "Coin", ["money", "finance"]),
  icon("credit-card", "Credit card", ["payment", "money"]),
  icon("cube", "Cube", ["package", "component"]),
  icon("database", "Database", ["data", "storage"]),
  icon("device-desktop", "Desktop", ["computer", "screen"]),
  icon("download", "Download", ["save", "export"]),
  icon("edit", "Edit", ["pencil", "change"]),
  icon("external-link", "External link", ["open", "new tab"]),
  icon("eye", "Eye", ["view", "preview"]),
  icon("file", "File", ["document"]),
  icon("file-code", "Code file", ["source", "developer"]),
  icon("file-text", "Document", ["text", "docs"]),
  icon("filter", "Filter", ["refine", "search"]),
  icon("flag", "Flag", ["marker", "country"]),
  icon("folder", "Folder", ["directory", "files"]),
  icon("heart", "Heart", ["favorite", "health"]),
  icon("help-circle", "Help", ["question", "support"]),
  icon("home", "Home", ["start", "dashboard"]),
  icon("info-circle", "Info", ["information", "help"]),
  icon("key", "Key", ["access", "security"]),
  icon("layout-dashboard", "Dashboard", ["layout", "overview"]),
  icon("link", "Link", ["url", "connection"]),
  icon("list", "List", ["items", "rows"]),
  icon("lock", "Lock", ["security", "private"]),
  icon("mail", "Mail", ["email", "message"]),
  icon("map-pin", "Map pin", ["location", "place"]),
  icon("message", "Message", ["chat", "comment"]),
  icon("microphone", "Microphone", ["audio", "voice"]),
  icon("note", "Note", ["memo", "writing"]),
  icon("package", "Package", ["box", "module"]),
  icon("palette", "Palette", ["color", "design"]),
  icon("photo", "Photo", ["image", "picture"]),
  icon("player-play", "Play", ["start", "media"]),
  icon("plus", "Plus", ["add", "create"]),
  icon("search", "Search", ["find", "lookup"]),
  icon("send", "Send", ["submit", "deliver"]),
  icon("server", "Server", ["host", "infrastructure"]),
  icon("settings", "Settings", ["configure", "preferences"]),
  icon("shield", "Shield", ["security", "protection"]),
  icon("sparkles", "Sparkles", ["ai", "magic"]),
  icon("star", "Star", ["favorite", "rating"]),
  icon("tag", "Tag", ["label", "category"]),
  icon("tool", "Tool", ["build", "maintenance"]),
  icon("trash", "Trash", ["delete", "remove"]),
  icon("upload", "Upload", ["import", "file"]),
  icon("user", "User", ["person", "account"]),
  icon("users", "Users", ["people", "team"]),
  icon("video", "Video", ["camera", "media"]),
  icon("world", "World", ["globe", "web"]),
  icon("x", "Close", ["cancel", "remove"]),
] as const;
