export { default as accountsApp, service as accountsService } from "@/accounts";
export { default as contactsApp, service as contactsService } from "@/contacts";
export { default as faqApp, service as faqService } from "@/faq";
export { default as filesApp, service as filesService } from "@/files";
export { default as hostsApp, service as hostsService } from "@/hosts";
export { default as loggingApp, service as loggingService } from "@/logging";
export { default as notebooksApp, service as notebooksService } from "@/notebooks";
export { default as notificationsApp, service as notificationsService } from "@/notifications";
export { default as oauthApp, service as oauthService } from "@/oauth";
export { default as proxyAuthApp, service as proxyAuthService } from "@/proxy-auth";
export { default as quotesApp, service as quotesService } from "@/quotes";
export { default as settingsApp, service as settingsService } from "@/settings";
export { default as spacesApp, service as spacesService } from "@/spaces";
export { default as syncApp, service as syncService } from "@/sync";
export { default as termsApp, service as termsService } from "@/terms";
export { default as toolsApp, service as toolsService } from "@/tools";
export { default as uiLabApp, service as uiLabService } from "@/ui-lab";
export { default as weatherApp, service as weatherService } from "@/weather";

export type { ApiType as AccountsApiType } from "@/accounts";
export type { ApiType as ContactsApiType } from "@/contacts";
export type { ApiType as FaqApiType } from "@/faq";
export type { ApiType as FilesApiType } from "@/files";
export type { ApiType as HostsApiType } from "@/hosts";
export type { ApiType as LoggingApiType } from "@/logging";
export type { ApiType as NotebooksApiType } from "@/notebooks";
export type { ApiType as NotificationsApiType } from "@/notifications";
export type { ApiType as OauthApiType } from "@/oauth";
export type { ApiType as ProxyAuthApiType } from "@/proxy-auth";
export type { ApiType as QuotesApiType } from "@/quotes";
export type { ApiType as SettingsApiType } from "@/settings";
export type { ApiType as SpacesApiType } from "@/spaces";
export type { ApiType as SyncApiType } from "@/sync";
export type { ApiType as TermsApiType } from "@/terms";
export type { ApiType as WeatherApiType } from "@/weather";
