export const generatedReferenceHeader = "<!-- Generated by docs-site/scripts/generate-cloud-dev-references.ts. Do not edit. -->";

export const isGeneratedReference = (source: string): boolean => source.replaceAll("\r\n", "\n").startsWith(generatedReferenceHeader);

export const obsoleteGeneratedReferences = (
  existing: Iterable<{ name: string; source: string }>,
  expected: ReadonlySet<string>,
): string[] =>
  [...existing]
    .filter(({ name }) => name.endsWith(".md") && !expected.has(name))
    .filter(({ source }) => isGeneratedReference(source))
    .map(({ name }) => name)
    .sort();

export const generatedAnchors = (markdown: string, output: string): Set<string> => {
  const anchors = new Set<string>();
  for (const match of markdown.matchAll(/<a id="([^"]+)"><\/a>/g)) {
    const anchor = match[1];
    if (anchors.has(anchor)) {
      throw new Error(`${output}: duplicate generated anchor ${anchor}`);
    }
    anchors.add(anchor);
  }
  return anchors;
};

export const portableWebsiteTarget = (target: string): string =>
  target === "/ui" || target.startsWith("/ui/") ? "./components.md" : target;
