/**
 * Curated list of tabler icon options for use in select inputs.
 * Each entry has an `id` (icon class without `ti-` prefix is the tabler name,
 * but stored as `ti-<name>` to match usage like `ti ti-<name>`),
 * a human-readable `label`, and an `icon` class string for rendering.
 */
export const ICON_OPTIONS = [
  // Documents & Writing
  { id: "ti-notebook", label: "Notebook", icon: "ti ti-notebook" },
  { id: "ti-book", label: "Book", icon: "ti ti-book" },
  { id: "ti-note", label: "Note", icon: "ti ti-note" },
  { id: "ti-notes", label: "Notes", icon: "ti ti-notes" },
  { id: "ti-file-text", label: "Document", icon: "ti ti-file-text" },
  { id: "ti-file-code", label: "Code", icon: "ti ti-file-code" },
  { id: "ti-clipboard", label: "Clipboard", icon: "ti ti-clipboard" },
  { id: "ti-list-check", label: "Checklist", icon: "ti ti-list-check" },
  { id: "ti-bookmark", label: "Bookmark", icon: "ti ti-bookmark" },
  { id: "ti-pencil", label: "Pencil", icon: "ti ti-pencil" },
  { id: "ti-quote", label: "Quote", icon: "ti ti-quote" },
  { id: "ti-tag", label: "Tag", icon: "ti ti-tag" },
  // Objects
  { id: "ti-star", label: "Star", icon: "ti ti-star" },
  { id: "ti-heart", label: "Heart", icon: "ti ti-heart" },
  { id: "ti-diamond", label: "Diamond", icon: "ti ti-diamond" },
  { id: "ti-crown", label: "Crown", icon: "ti ti-crown" },
  { id: "ti-trophy", label: "Trophy", icon: "ti ti-trophy" },
  { id: "ti-flag", label: "Flag", icon: "ti ti-flag" },
  { id: "ti-key", label: "Key", icon: "ti ti-key" },
  { id: "ti-lock", label: "Lock", icon: "ti ti-lock" },
  { id: "ti-shield", label: "Shield", icon: "ti ti-shield" },
  { id: "ti-gift", label: "Gift", icon: "ti ti-gift" },
  { id: "ti-bell", label: "Bell", icon: "ti ti-bell" },
  { id: "ti-lamp", label: "Lamp", icon: "ti ti-lamp" },
  { id: "ti-bolt", label: "Bolt", icon: "ti ti-bolt" },
  { id: "ti-bulb", label: "Idea", icon: "ti ti-bulb" },
  { id: "ti-puzzle", label: "Puzzle", icon: "ti ti-puzzle" },
  { id: "ti-eye", label: "Eye", icon: "ti ti-eye" },
  { id: "ti-brain", label: "Brain", icon: "ti ti-brain" },
  { id: "ti-compass", label: "Compass", icon: "ti ti-compass" },
  { id: "ti-wand", label: "Wand", icon: "ti ti-wand" },
  { id: "ti-sword", label: "Sword", icon: "ti ti-sword" },
  { id: "ti-anchor", label: "Anchor", icon: "ti ti-anchor" },
  { id: "ti-camera", label: "Camera", icon: "ti ti-camera" },
  { id: "ti-music", label: "Music", icon: "ti ti-music" },
  { id: "ti-palette", label: "Palette", icon: "ti ti-palette" },
  { id: "ti-paint", label: "Paint", icon: "ti ti-paint" },
  { id: "ti-coffee", label: "Coffee", icon: "ti ti-coffee" },
  // Animals
  { id: "ti-cat", label: "Cat", icon: "ti ti-cat" },
  { id: "ti-dog", label: "Dog", icon: "ti ti-dog" },
  { id: "ti-fish", label: "Fish", icon: "ti ti-fish" },
  { id: "ti-bug", label: "Bug", icon: "ti ti-bug" },
  { id: "ti-butterfly", label: "Butterfly", icon: "ti ti-butterfly" },
  { id: "ti-feather", label: "Feather", icon: "ti ti-feather" },
  { id: "ti-paw", label: "Paw", icon: "ti ti-paw" },
  { id: "ti-deer", label: "Deer", icon: "ti ti-deer" },
  { id: "ti-horse", label: "Horse", icon: "ti ti-horse" },
  { id: "ti-pig", label: "Pig", icon: "ti ti-pig" },
  { id: "ti-spider", label: "Spider", icon: "ti ti-spider" },
  { id: "ti-bat", label: "Bat", icon: "ti ti-bat" },
  // Nature & Weather
  { id: "ti-flower", label: "Flower", icon: "ti ti-flower" },
  { id: "ti-leaf", label: "Leaf", icon: "ti ti-leaf" },
  { id: "ti-tree", label: "Tree", icon: "ti ti-tree" },
  { id: "ti-plant", label: "Plant", icon: "ti ti-plant" },
  { id: "ti-seeding", label: "Seeding", icon: "ti ti-seeding" },
  { id: "ti-mushroom", label: "Mushroom", icon: "ti ti-mushroom" },
  { id: "ti-cactus", label: "Cactus", icon: "ti ti-cactus" },
  { id: "ti-sun", label: "Sun", icon: "ti ti-sun" },
  { id: "ti-moon", label: "Moon", icon: "ti ti-moon" },
  { id: "ti-cloud", label: "Cloud", icon: "ti ti-cloud" },
  { id: "ti-snowflake", label: "Snowflake", icon: "ti ti-snowflake" },
  { id: "ti-flame", label: "Flame", icon: "ti ti-flame" },
  { id: "ti-rainbow", label: "Rainbow", icon: "ti ti-rainbow" },
  { id: "ti-tornado", label: "Tornado", icon: "ti ti-tornado" },
  { id: "ti-mountain", label: "Mountain", icon: "ti ti-mountain" },
  // Travel & Space
  { id: "ti-home", label: "Home", icon: "ti ti-home" },
  { id: "ti-world", label: "World", icon: "ti ti-world" },
  { id: "ti-globe", label: "Globe", icon: "ti ti-globe" },
  { id: "ti-map", label: "Map", icon: "ti ti-map" },
  { id: "ti-rocket", label: "Rocket", icon: "ti ti-rocket" },
  { id: "ti-planet", label: "Planet", icon: "ti ti-planet" },
  { id: "ti-meteor", label: "Meteor", icon: "ti ti-meteor" },
  { id: "ti-comet", label: "Comet", icon: "ti ti-comet" },
  { id: "ti-tent", label: "Tent", icon: "ti ti-tent" },
  { id: "ti-sailboat", label: "Sailboat", icon: "ti ti-sailboat" },
  { id: "ti-plane", label: "Plane", icon: "ti ti-plane" },
  // Food & Drink
  { id: "ti-apple", label: "Apple", icon: "ti ti-apple" },
  { id: "ti-cherry", label: "Cherry", icon: "ti ti-cherry" },
  { id: "ti-lemon", label: "Lemon", icon: "ti ti-lemon" },
  { id: "ti-pizza", label: "Pizza", icon: "ti ti-pizza" },
  { id: "ti-cake", label: "Cake", icon: "ti ti-cake" },
  { id: "ti-cookie", label: "Cookie", icon: "ti ti-cookie" },
  { id: "ti-candy", label: "Candy", icon: "ti ti-candy" },
  { id: "ti-ice-cream", label: "Ice Cream", icon: "ti ti-ice-cream" },
  // Fun
  { id: "ti-ghost", label: "Ghost", icon: "ti ti-ghost" },
  { id: "ti-alien", label: "Alien", icon: "ti ti-alien" },
  { id: "ti-atom", label: "Atom", icon: "ti ti-atom" },
];

export type IconOption = (typeof ICON_OPTIONS)[number];

export const icons = {
  ICON_OPTIONS,
  options: ICON_OPTIONS,
} as const;
